import type { CapacitorConfig } from "@capacitor/cli";

const config: CapacitorConfig = {
  appId: "com.kahli.marketplace",
  appName: "KAHEEL",
  // Native releases ship the reviewed SPA generated by `npm run build:mobile`.
  // No production binary is allowed to load its application code from server.url.
  webDir: "dist/client",
  loggingBehavior: "none",
  zoomEnabled: false,
  server: {
    hostname: "localhost",
    androidScheme: "https",
    cleartext: false,
  },
  android: {
    allowMixedContent: false,
    useLegacyBridge: false,
    webContentsDebuggingEnabled: false,
  },
  ios: {
    allowsLinkPreview: false,
    webContentsDebuggingEnabled: false,
  },
  includePlugins: [
    "@capacitor/app",
    "@capacitor/preferences",
    "capacitor-secure-storage-plugin",
  ],
};

export default config;
