-- =====================================================================
-- ROLLBACK for .lovable/pending-migrations/20260812_acl_hardening.sql
-- Generated object-by-object from the documented snapshot
--   .lovable/audit/2026-08-12-acl-snapshot.md
-- Snapshot integrity: signature-list md5 = 2848b8d566e1ce2ab5f40219c1dcc05c
--
-- Each statement restores EXACTLY the grant that the hardening migration
-- removed from that object. Nothing else is granted. No blanket GRANT.
-- =====================================================================

BEGIN;

GRANT EXECUTE ON FUNCTION public.mkt_account_country_id(uuid) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_activities_block_delete() TO PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.mkt_activities_guard() TO PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.mkt_activity_migration_report() TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_activity_normalize() TO PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.mkt_activity_prune() TO PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.mkt_admin_activities(text,uuid,boolean,integer) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_admin_add_note(text,uuid,text) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_admin_assignments_for(text,uuid[]) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_admin_assignments_kind_guard() TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.mkt_admin_audit_log(text,text,integer,integer) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_admin_business_detail(uuid) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_admin_businesses(text,integer,integer) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_admin_call_abuse(integer) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_admin_can(text) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_admin_category_demote(uuid,uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.mkt_admin_category_merge(uuid,uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.mkt_admin_category_move(uuid,uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.mkt_admin_category_promote(uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.mkt_admin_category_set_active(uuid,boolean) TO anon;
GRANT EXECUTE ON FUNCTION public.mkt_admin_category_upsert(uuid,uuid,text,text,text,text,text,integer) TO anon;
GRANT EXECUTE ON FUNCTION public.mkt_admin_claim(text,uuid) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_admin_create_activity(uuid,text,text,uuid) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_admin_create_group(text,text,text,integer) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_admin_grant_points(text,uuid,integer,text) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_admin_listing_action(uuid,text,text,integer) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_admin_listing_brief(uuid) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_admin_listing_create_for(uuid,uuid,text,text) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_admin_listing_detail(uuid) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_admin_listing_events(text,text,uuid,timestamp with time zone,timestamp with time zone,integer,integer) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_admin_listing_extend(uuid,integer) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_admin_listing_moderation(uuid) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_admin_listing_reports(text,text,text,text,uuid,timestamp with time zone,timestamp with time zone,boolean,integer,integer) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_admin_log_doc_access(text,uuid,text) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_admin_moderation_rule_delete(uuid,text) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_admin_moderation_rule_save(uuid,text,text,text,text,text,text,integer,boolean,text) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_admin_notes_list(text,uuid) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_admin_notify_user(uuid,text,text) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_admin_overview() TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.mkt_admin_refund_promotion(uuid,text) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_admin_release(text,uuid,text) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_admin_rescan_listing(uuid) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_admin_run_tick() TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_admin_scan_dismiss(uuid,text) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_admin_search(text,integer) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_admin_set_setting(text,jsonb,text) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_admin_slot_discard_draft(text) TO anon;
GRANT EXECUTE ON FUNCTION public.mkt_admin_slot_publish(text) TO anon;
GRANT EXECUTE ON FUNCTION public.mkt_admin_slot_set_draft(text,jsonb) TO anon;
GRANT EXECUTE ON FUNCTION public.mkt_admin_slot_undo(text) TO anon;
GRANT EXECUTE ON FUNCTION public.mkt_admin_store_action(uuid,text,text) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_admin_store_audit(uuid,integer) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_admin_stores(text,text,text,integer,integer) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_admin_subject_action(text,uuid,text,text,integer) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_admin_subject_ids(uuid[],uuid[]) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_admin_transfer(text,uuid,uuid,text) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_admin_update_activity(uuid,text,text,boolean) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_admin_update_group(uuid,text,text,boolean,integer) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_admin_user_detail(uuid) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_admin_users(text,integer,integer) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_admin_verification_detail(uuid) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_advertiser_safety(uuid,uuid) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_ai_usage_recent(text,integer) TO anon;
GRANT EXECUTE ON FUNCTION public.mkt_analytics_fields(integer) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_analytics_funnel(integer) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_analytics_geo(integer) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_analytics_guard() TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_analytics_health(integer) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_analytics_listings(integer) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_analytics_ops(integer) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_analytics_overview() TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_analytics_people(integer,integer) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_analytics_purge_expired() TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.mkt_analytics_report(integer,boolean) TO anon;
GRANT EXECUTE ON FUNCTION public.mkt_analytics_retention_get() TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_analytics_retention_set(integer,text) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.mkt_analytics_rollup(timestamp with time zone) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.mkt_analytics_search(integer,integer) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_analytics_timeseries(integer) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_append_only_guard() TO PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.mkt_assert_city_in_country() TO PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.mkt_attendance_admin_set(uuid,date,timestamp with time zone,timestamp with time zone,boolean,text,text,text) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_attendance_approve(uuid,text) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_attendance_can_approve() TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_attendance_can_manage() TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_attendance_can_view() TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_attendance_check_in(boolean,text) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_attendance_check_out(text) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_attendance_edits_list(uuid) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_attendance_list(date,date,uuid) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_attendance_my(date,date) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_attendance_recompute(uuid) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.mkt_bank_accounts_for(text) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_bank_request_respond(uuid,text) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_bank_request_send(uuid,text) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_bank_share(uuid,uuid,text,uuid) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_business_details_complete(uuid) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_business_is_restricted(uuid) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_business_number_taken(text,text) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_call_can_call(uuid) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_call_can_call_conv(uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.mkt_call_missed(uuid,text) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_call_mode(uuid,uuid) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_call_mode_set(uuid,text) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_call_peer(uuid) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_call_request_close(uuid,text) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_call_request_create(uuid) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_call_request_start(uuid) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_call_settings_sync() TO PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.mkt_call_start(uuid) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_call_start_conv(uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.mkt_call_stop_receiving() TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_call_transition(uuid,text,text) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_calls_sweep() TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_can_manage_business(uuid) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_can_manage_listing(uuid) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_can_review_identity() TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_can_view_conversation(uuid) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_can_view_quote(uuid) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_cart_item_guard() TO PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.mkt_cart_item_owner(uuid) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_cart_owner(uuid) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_categories_depth_guard() TO PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.mkt_categories_no_duplicate() TO PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.mkt_category_world_slots(text,text) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_chat_block_set(uuid,boolean) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_chat_blocked(uuid,uuid) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_chat_peer(uuid) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_commerce_flags() TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_content_can(text) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_conversation_context(uuid) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_conversation_fill_seller() TO PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.mkt_conversation_mark_read(uuid) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_conversation_open(uuid) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_conversation_state_set(uuid,boolean,boolean) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_conversations_list() TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_demo_interaction_guard() TO authenticated;
GRANT EXECUTE ON FUNCTION public.mkt_demo_notification_guard() TO authenticated;
GRANT EXECUTE ON FUNCTION public.mkt_departments_manage() TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_distance_m(double precision,double precision,double precision,double precision) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_enforce_listing(uuid,text,text,integer) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_enforce_listing_price() TO PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.mkt_enqueue_storage_cleanup() TO PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.mkt_entity_activities_guard() TO PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.mkt_entity_activities_list(uuid) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_errand_advance(uuid,text) TO anon;
GRANT EXECUTE ON FUNCTION public.mkt_errand_cancel(uuid,text) TO anon;
GRANT EXECUTE ON FUNCTION public.mkt_errand_decide_offer(uuid,boolean) TO anon;
GRANT EXECUTE ON FUNCTION public.mkt_errand_place_offer(uuid,numeric,integer,text) TO anon;
GRANT EXECUTE ON FUNCTION public.mkt_errand_rate(uuid,integer,text) TO anon;
GRANT EXECUTE ON FUNCTION public.mkt_expire_re_licenses() TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_force_account_country() TO PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.mkt_guard_business_insert() TO PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.mkt_guard_business_verification() TO PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.mkt_guard_listing_promotion() TO PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.mkt_guard_listing_status() TO PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.mkt_guard_restrictions() TO PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.mkt_guide_featured_places(integer) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.mkt_guide_force_pending() TO PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.mkt_guide_place_is_owner(uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.mkt_guide_place_rating(uuid) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.mkt_guide_places_block_forbidden() TO PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.mkt_guide_promote_place(uuid,integer,uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.mkt_guide_provider_category(text,text,text) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_guide_review_claim(uuid,boolean,text) TO anon;
GRANT EXECUTE ON FUNCTION public.mkt_guide_review_photo(uuid,boolean,text) TO anon;
GRANT EXECUTE ON FUNCTION public.mkt_guide_review_review(uuid,boolean,text) TO anon;
GRANT EXECUTE ON FUNCTION public.mkt_guide_touch_updated_at() TO PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.mkt_has_restriction(text,uuid,text[]) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_increment_views(uuid) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.mkt_is_auto_publish_op() TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_is_business_principal(uuid) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_is_call_party(uuid) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_is_listing_op() TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_is_moderation_op() TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_is_platform_admin() TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.mkt_is_super_admin() TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_is_system_action() TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_is_system_owner() TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_is_verified_business(uuid) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_license_guard() TO PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.mkt_license_private_touch() TO PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.mkt_lift_expired_restrictions() TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_lift_restriction(uuid,text) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_listing_archive(uuid) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_listing_before_write() TO PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.mkt_listing_commerce_action(uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.mkt_listing_content_rescan() TO PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.mkt_listing_delete(uuid) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_listing_duplicate(uuid) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_listing_event_log(uuid,integer) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_listing_events_immutable() TO PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.mkt_listing_exact_location(uuid) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_listing_freeze_owner() TO PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.mkt_listing_image_delete(uuid,uuid) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_listing_image_set_cover(uuid,uuid) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_listing_image_sync_keys() TO PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.mkt_listing_images_reorder(uuid,uuid[]) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_listing_images_required(uuid) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_listing_is_public(uuid) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.mkt_listing_log_status() TO PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.mkt_listing_pause(uuid) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_listing_price_change_audit() TO PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.mkt_listing_promote(uuid,integer,text) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_listing_promotion_overview(uuid) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_listing_reactivate(uuid) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_listing_renew(uuid,integer) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_listing_republish(uuid,integer,text) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_listing_require_business_details() TO PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.mkt_listing_restore(uuid) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_listing_resume(uuid) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_listing_store_link_guard() TO PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.mkt_listing_submit(uuid) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_listing_track(uuid,text) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.mkt_listing_track_share(uuid) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.mkt_listing_validate() TO PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.mkt_listing_workforce_sync() TO PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.mkt_listings_geo_currency() TO PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.mkt_log_listing_event(uuid,text,jsonb) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_mascot_phrases_touch() TO PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.mkt_merge_activities(uuid,uuid,text) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_message_bump_conversation() TO PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.mkt_message_delete(uuid,text) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_message_reports_guard() TO authenticated;
GRANT EXECUTE ON FUNCTION public.mkt_message_send(uuid,text,text,jsonb,uuid) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_moderation_check_text(text) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_moderation_normalize(text) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_moderation_rule_normalize() TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.mkt_moderation_scan_listing(uuid,text) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.mkt_my_moderation_cases() TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_my_platform_role() TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_my_storefront(text) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_nearby_directory(double precision,double precision,double precision,integer,integer,text,text,text) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.mkt_nearby_guide_places(double precision,double precision,double precision,integer,integer,text,text,text,text,text,text) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.mkt_nearby_listings(double precision,double precision,double precision,integer,integer,uuid,uuid,uuid,uuid,text,text,numeric,numeric,text,text,boolean,boolean,boolean) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.mkt_nearby_storefronts(double precision,double precision,double precision,integer,integer,uuid,uuid,text,text) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.mkt_norm_activity_text(text) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_norm_digits(text) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_norm_label(text) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_notify(uuid,uuid,text,text,text) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_officer_guard() TO PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.mkt_ops_log_append_only() TO authenticated;
GRANT EXECUTE ON FUNCTION public.mkt_order_after() TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.mkt_order_before() TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.mkt_order_item_party(uuid) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_order_party(uuid) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_perm_aliases(text) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_person_is_restricted(uuid) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_promotion_prices() TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_provider_categories_public() TO anon;
GRANT EXECUTE ON FUNCTION public.mkt_provider_directory(text,text,integer) TO anon;
GRANT EXECUTE ON FUNCTION public.mkt_public_business(text) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.mkt_public_business_categories(text) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.mkt_public_business_listings(text,uuid,integer,integer) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.mkt_public_person(text) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.mkt_public_person_categories(text) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.mkt_public_person_listings(text,uuid,integer,integer) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.mkt_public_phone(uuid) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.mkt_qa_cleanup(text) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_quote_fill_seller() TO PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.mkt_re_booking_decide(uuid,boolean,text) TO anon;
GRANT EXECUTE ON FUNCTION public.mkt_re_booking_set_expiry() TO authenticated;
GRANT EXECUTE ON FUNCTION public.mkt_re_expire_bookings() TO anon;
GRANT EXECUTE ON FUNCTION public.mkt_re_guard_booking_update() TO PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.mkt_re_guard_provider_update() TO PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.mkt_re_license_active(uuid) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.mkt_re_listing_published(uuid) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.mkt_re_lock_provider_type() TO authenticated;
GRANT EXECUTE ON FUNCTION public.mkt_re_photos_limit() TO authenticated;
GRANT EXECUTE ON FUNCTION public.mkt_re_promote_listing(uuid,integer,integer) TO anon;
GRANT EXECUTE ON FUNCTION public.mkt_re_provider_slugify(text,uuid) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_re_providers_slug_fill() TO PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.mkt_re_soft_delete_guard() TO authenticated;
GRANT EXECUTE ON FUNCTION public.mkt_re_sync_sort_price() TO authenticated;
GRANT EXECUTE ON FUNCTION public.mkt_re_verification_review(uuid,boolean,text) TO anon;
GRANT EXECUTE ON FUNCTION public.mkt_registry_guard() TO PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.mkt_report_apply_status(uuid,text,text) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_report_assign(uuid,uuid) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_report_close(uuid,text,text,text) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_report_conflict(uuid) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_report_is_advertiser(uuid) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_report_is_reporter(uuid) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_report_listing_action(uuid,text,text,integer) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_report_merge(uuid,uuid) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_report_message(uuid,text,text,text,integer,text) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_report_note(uuid,text) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_report_reopen(uuid,text) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_report_reply(uuid,text,text) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_report_require(uuid,text) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_report_set_priority(uuid,text,text) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_report_set_status(uuid,text,text) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_report_staff_can_view(uuid) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_report_staff_options() TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_report_stats() TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_report_transition(uuid,text,text) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_report_transition_ok(text,text) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_report_workforce_sync() TO PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.mkt_require_re_license() TO PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.mkt_reset_phone_status() TO PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.mkt_restrict_subject(uuid,text,uuid,text,text,integer) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_review_activity_suggestion(uuid,text,uuid,text) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_review_appeal(uuid,text,text) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_review_listing(uuid,text,text) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_review_verification(uuid,text,text) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_root_category(uuid) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_run_scheduled_jobs(text) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_search_activities(text,uuid,uuid,boolean,integer) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_search_stores(text,text,integer) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_service_booking_action(uuid,text,text,text) TO anon;
GRANT EXECUTE ON FUNCTION public.mkt_service_create_booking(text,uuid,timestamp with time zone,uuid,text,text,text,text,double precision,double precision,text,text) TO anon;
GRANT EXECUTE ON FUNCTION public.mkt_service_provider_save(text,jsonb,jsonb) TO anon;
GRANT EXECUTE ON FUNCTION public.mkt_service_provider_setup(text) TO anon;
GRANT EXECUTE ON FUNCTION public.mkt_service_review_save(uuid,smallint,text) TO anon;
GRANT EXECUTE ON FUNCTION public.mkt_service_store_bootstrap() TO PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.mkt_set_entity_activities(uuid,uuid,uuid[]) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_set_listing_status(uuid,text,text) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_shift_for(uuid,date) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_shift_set(uuid,date,text,time without time zone,time without time zone,boolean,text,text) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_shifts_list(date,date,uuid) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_slot_apply(text,jsonb) TO anon;
GRANT EXECUTE ON FUNCTION public.mkt_slot_rotation_check() TO PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.mkt_slot_sanitize_patch(jsonb) TO anon;
GRANT EXECUTE ON FUNCTION public.mkt_slot_snapshot(text) TO anon;
GRANT EXECUTE ON FUNCTION public.mkt_slugify(text) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_staff_eligible(uuid,text) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_staff_has(text) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_staff_leave_validate() TO PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.mkt_staff_on_leave(uuid) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_staff_on_leave_at(uuid,date) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_staff_on_shift(uuid) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_staff_specialist(uuid,text) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_staff_status_coherence() TO PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.mkt_store_addon_group_guard() TO PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.mkt_store_addon_group_manage(uuid) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_store_addon_group_visible(uuid) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.mkt_store_addon_guard() TO PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.mkt_store_admin() TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.mkt_store_branch_manage(uuid) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_store_branch_visible(uuid) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.mkt_store_draft(text) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_store_hours_guard() TO PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.mkt_store_hours_save(uuid,jsonb) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_store_item_guard() TO PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.mkt_store_item_manage(uuid) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_store_item_visible(uuid) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.mkt_store_linkable_listings(text) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_store_open_state(uuid) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.mkt_store_overview(text) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_store_public(text) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.mkt_store_public_phone(uuid) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_store_qa_cleanup(text) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_store_section_guard() TO PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.mkt_store_submit(uuid) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_store_touch() TO PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.mkt_store_visible(uuid) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.mkt_store_zones_save(uuid,jsonb) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_storefront_after_insert() TO PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.mkt_storefront_guard() TO PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.mkt_student_bot_state() TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.mkt_student_bot_touch() TO PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.mkt_submit_appeal(uuid,text) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_submit_report(uuid,text,text,boolean) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_suggest_activity(text,uuid,uuid,uuid) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_support_tickets_guard() TO authenticated;
GRANT EXECUTE ON FUNCTION public.mkt_sweep_expired_listings() TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_sweep_expired_re_licenses() TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_sweep_promotion_notices() TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_sync_favorites_count() TO PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.mkt_sync_quote_requests_count() TO PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.mkt_sync_reports_count() TO PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.mkt_syria_directory_entry_guard() TO PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.mkt_syria_directory_name_requires_review(text,text,text) TO anon;
GRANT EXECUTE ON FUNCTION public.mkt_syria_guide_facets_v1() TO anon;
GRANT EXECUTE ON FUNCTION public.mkt_syria_guide_search_v1(text,text,text,text,integer,integer) TO anon;
GRANT EXECUTE ON FUNCTION public.mkt_syria_institute_search_guard() TO PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.mkt_syria_normalize(text) TO anon;
GRANT EXECUTE ON FUNCTION public.mkt_syria_program_search_guard() TO PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.mkt_template_layout_check() TO PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.mkt_theme_active() TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.mkt_theme_palette_activate(uuid) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_theme_palette_delete(uuid) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_theme_palette_list() TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_theme_palette_save(uuid,text,jsonb,boolean) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_theme_reset_default() TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_theme_token_draft_set(uuid,text,text,text) TO anon;
GRANT EXECUTE ON FUNCTION public.mkt_theme_tokens_admin(uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.mkt_theme_tokens_apply(uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.mkt_theme_tokens_discard(uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.mkt_track(jsonb) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.mkt_ui_labels_touch() TO PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.mkt_user_blocked(text[]) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_user_can(uuid,text) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_user_profile_before_write() TO PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.mkt_verification_file_delete_guard() TO PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.mkt_verification_request_requires_details() TO PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.mkt_verification_request_submitted() TO PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.mkt_verification_workforce_sync() TO PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.mkt_wallet_for_listing(uuid) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.mkt_workforce_add_leave(uuid,text,date,date,text,uuid) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_workforce_assigned_today(uuid) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_workforce_autoqueue(text,uuid,text) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_workforce_can_take(uuid,text) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_workforce_cancel_leave(uuid,text) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_workforce_close_item(text,uuid) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_workforce_department_save(text,text,text,text[],integer,boolean,boolean,text) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_workforce_departments_overview() TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_workforce_distribute(text,integer) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_workforce_done_today(uuid) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_workforce_enqueue(text,uuid,text,timestamp with time zone) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_workforce_is_staff() TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_workforce_kind_save(text,text,text,text,text,text,integer,boolean,boolean) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_workforce_manage() TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_workforce_my_status() TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_workforce_open_count(uuid) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_workforce_overdue_count(uuid) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_workforce_override_assign(text,uuid,uuid,text) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_workforce_overview() TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_workforce_pick_assignee(text) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_workforce_queue(text,text,integer) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_workforce_reassign_from(uuid,text) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_workforce_refresh_leave_states() TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_workforce_reopen_item(text,uuid,text) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_workforce_require_attendance() TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.mkt_workforce_set_priority(text,uuid,text,text) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_workforce_set_progress(text,uuid,text) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_workforce_set_staff(uuid,text,integer,boolean,text,text,text) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_workforce_set_staff_profile(uuid,text,text[],text[],integer,integer,uuid,text) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_workforce_specialty_save(text,text,text,text,integer,boolean) TO PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mkt_workforce_staff() TO PUBLIC, anon;

COMMIT;

-- statements: 429
