export const MARKET_URL = import.meta.env.VITE_KAHEEL_MARKET_URL?.trim() || "/";
export const AUTH_URL = "/auth?next=%2Fappointments";
export const REGISTER_URL = "/register";
export const today = () => new Date().toISOString().slice(0, 10);
export const weekdaysAr = ["الأحد", "الاثنين", "الثلاثاء", "الأربعاء", "الخميس", "الجمعة", "السبت"];
export const weekdaysEn = ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"];

export const statusAr: Record<string, string> = {
  requested: "بانتظار التأكيد",
  confirmed: "مؤكد",
  checked_in: "تم الوصول",
  in_service: "جاري تقديم الخدمة",
  completed: "مكتمل",
  cancelled_by_customer: "ألغاه العميل",
  cancelled_by_provider: "ألغاه مقدم الخدمة",
  rejected: "مرفوض",
  no_show: "لم يحضر",
  waiting: "في الانتظار",
  called: "تم النداء",
  serving: "جاري الخدمة",
  done: "مكتمل",
  skipped: "تم التجاوز",
  cancelled: "ملغي",
};

export const statusEn: Record<string, string> = {
  requested: "Pending confirmation",
  confirmed: "Confirmed",
  checked_in: "Checked in",
  in_service: "In service",
  completed: "Completed",
  cancelled_by_customer: "Cancelled by customer",
  cancelled_by_provider: "Cancelled by provider",
  rejected: "Rejected",
  no_show: "No show",
  waiting: "Waiting",
  called: "Called",
  serving: "Serving",
  done: "Done",
  skipped: "Skipped",
  cancelled: "Cancelled",
};

export function getCopy(isAr: boolean) {
  return isAr
    ? {
        brand: "كَحيل مواعيد",
        subBrand: "KAHEEL Appointments",
        market: "اذهب إلى سوق كَحيل",
        signIn: "تسجيل الدخول",
        register: "إنشاء حساب",
        discover: "احجز موعدًا",
        mine: "مواعيدي",
        provider: "تقديم الخدمة",
        hero: "موعدك أوضح، وانتظارك أقصر.",
        heroBody: "تطبيق مستقل لحجز المواعيد وقوائم الانتظار، مرتبط بحساب كَحيل الموحد دون الاعتماد على بيانات السوق.",
        search: "ابحث عن مقدم خدمة أو خدمة",
        city: "المدينة",
        searchAction: "بحث",
        providers: "مقدمو الخدمة",
        noProviders: "لا توجد خدمات منشورة بعد",
        noProvidersBody: "ستظهر هنا الجهات التي تنشر خدماتها داخل كَحيل مواعيد.",
        chooseService: "اختر الخدمة",
        appointment: "موعد مسبق",
        queue: "انتظار مباشر",
        date: "التاريخ",
        slots: "الأوقات المتاحة",
        noSlots: "لا توجد أوقات متاحة في هذا اليوم.",
        name: "الاسم",
        phone: "رقم الجوال",
        notes: "ملاحظات اختيارية",
        confirm: "تأكيد الحجز",
        joinQueue: "دخول قائمة الانتظار",
        loginFirst: "سجّل الدخول بالحساب الموحد لإكمال الحجز.",
        saved: "تمت العملية بنجاح",
        upcoming: "الحجوزات",
        activeQueue: "قائمة الانتظار الحالية",
        noAppointments: "لا توجد مواعيد",
        noAppointmentsBody: "بعد حجز أول موعد سيظهر هنا بنفس حساب كَحيل.",
        queueNumber: "رقمك",
        ahead: "أمامك",
        people: "أشخاص",
        eta: "الوقت المتوقع",
        minutes: "دقيقة",
        cancel: "إلغاء",
        refresh: "تحديث",
        providerMode: "لوحة مقدم الخدمة",
        createProvider: "إنشاء حساب مقدم خدمة",
        providerName: "اسم مقدم الخدمة",
        englishName: "الاسم الإنجليزي (اختياري)",
        create: "إنشاء",
        selectProvider: "اختر حساب مقدم الخدمة",
        todayAppointments: "مواعيد اليوم",
        pending: "بانتظار التأكيد",
        liveQueue: "الانتظار النشط",
        completed: "المكتملة",
        providerEmpty: "لا يوجد حساب مقدم خدمة",
        providerEmptyBody: "أنشئ حسابًا مستقلًا للمواعيد؛ لن يُنشئ أو يعدل أي سجل في سوق كَحيل.",
        services: "الخدمات",
        addService: "إضافة خدمة",
        serviceName: "اسم الخدمة",
        duration: "المدة بالدقائق",
        price: "السعر",
        mode: "نوع الحجز",
        scheduled: "موعد مسبق",
        both: "موعد وانتظار",
        queueOnly: "انتظار فقط",
        active: "نشطة",
        inactive: "موقوفة",
        schedule: "ساعات العمل",
        start: "البداية",
        end: "النهاية",
        saveSchedule: "حفظ الجدول",
        settings: "الإعدادات والربط",
        publish: "نشر صفحة الحجز",
        pause: "إيقاف صفحة الحجز",
        accepting: "استقبال الحجوزات",
        instant: "تأكيد فوري",
        manual: "تأكيد يدوي",
        marketLink: "رابط سوق كَحيل (اختياري)",
        marketLinkHelp: "يُحفظ كرابط مستقل فقط، دون قراءة أو تعديل جداول السوق.",
        save: "حفظ",
        bookingLink: "رابط صفحة الحجز",
        copy: "نسخ",
        copied: "تم نسخ الرابط",
        providerAppointments: "مواعيد اليوم",
        providerQueue: "قائمة الانتظار",
        noToday: "لا توجد مواعيد لهذا اليوم.",
        noQueue: "قائمة الانتظار فارغة.",
      }
    : {
        brand: "KAHEEL Appointments",
        subBrand: "كَحيل مواعيد",
        market: "Go to KAHEEL Market",
        signIn: "Sign in",
        register: "Create account",
        discover: "Book",
        mine: "My appointments",
        provider: "Provide services",
        hero: "Clearer appointments. Shorter waits.",
        heroBody: "A standalone booking and live-queue app linked to the unified KAHEEL account without depending on Market data.",
        search: "Search for a provider or service",
        city: "City",
        searchAction: "Search",
        providers: "Service providers",
        noProviders: "No published services yet",
        noProvidersBody: "Providers published in KAHEEL Appointments will appear here.",
        chooseService: "Choose a service",
        appointment: "Scheduled appointment",
        queue: "Live queue",
        date: "Date",
        slots: "Available times",
        noSlots: "No available times on this date.",
        name: "Name",
        phone: "Mobile number",
        notes: "Optional notes",
        confirm: "Confirm booking",
        joinQueue: "Join live queue",
        loginFirst: "Sign in with the unified account to continue.",
        saved: "Completed successfully",
        upcoming: "Appointments",
        activeQueue: "Active queue",
        noAppointments: "No appointments",
        noAppointmentsBody: "Your first booking will appear here under the same KAHEEL account.",
        queueNumber: "Your number",
        ahead: "Ahead",
        people: "people",
        eta: "Estimated wait",
        minutes: "minutes",
        cancel: "Cancel",
        refresh: "Refresh",
        providerMode: "Provider dashboard",
        createProvider: "Create provider account",
        providerName: "Provider name",
        englishName: "English name (optional)",
        create: "Create",
        selectProvider: "Select provider account",
        todayAppointments: "Today's appointments",
        pending: "Pending confirmation",
        liveQueue: "Active queue",
        completed: "Completed",
        providerEmpty: "No provider account",
        providerEmptyBody: "Create a standalone appointments account; no KAHEEL Market record will be created or changed.",
        services: "Services",
        addService: "Add service",
        serviceName: "Service name",
        duration: "Duration in minutes",
        price: "Price",
        mode: "Booking mode",
        scheduled: "Scheduled",
        both: "Scheduled and queue",
        queueOnly: "Queue only",
        active: "Active",
        inactive: "Paused",
        schedule: "Working hours",
        start: "Start",
        end: "End",
        saveSchedule: "Save schedule",
        settings: "Settings and linking",
        publish: "Publish booking page",
        pause: "Pause booking page",
        accepting: "Accept bookings",
        instant: "Instant confirmation",
        manual: "Manual confirmation",
        marketLink: "KAHEEL Market link (optional)",
        marketLinkHelp: "Stored only as an independent link; Market tables are never read or modified.",
        save: "Save",
        bookingLink: "Booking page link",
        copy: "Copy",
        copied: "Link copied",
        providerAppointments: "Today's appointments",
        providerQueue: "Live queue",
        noToday: "No appointments on this date.",
        noQueue: "The queue is empty.",
      };
}

export type Copy = ReturnType<typeof getCopy>;
