/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BusinessRouteRouteImport } from './routes/business/route'
import { Route as ChooseAccountRouteImport } from './routes/choose-account'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as ErrandsRouteImport } from './routes/errands'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as GoRouteImport } from './routes/go'
import { Route as HelpRouteImport } from './routes/help'
import { Route as JoinRouteImport } from './routes/join'
import { Route as KidsRouteImport } from './routes/kids'
import { Route as MarketSetupRouteImport } from './routes/market-setup'
import { Route as MoreRouteImport } from './routes/more'
import { Route as MyRouteRouteImport } from './routes/my/route'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminAdCreditRouteImport } from './routes/admin/ad-credit'
import { Route as AdminApplicationsRouteImport } from './routes/admin/applications'
import { Route as AdminAuditLogRouteImport } from './routes/admin/audit-log'
import { Route as AdminBusinessesRouteImport } from './routes/admin/businesses'
import { Route as AdminCampaignsRouteImport } from './routes/admin/campaigns'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminErrandsRouteImport } from './routes/admin/errands'
import { Route as AdminGuideQueueRouteImport } from './routes/admin/guide-queue'
import { Route as AdminListingEventsRouteImport } from './routes/admin/listing-events'
import { Route as AdminListingReportsRouteImport } from './routes/admin/listing-reports'
import { Route as AdminListingsRouteImport } from './routes/admin/listings'
import { Route as AdminLocationsRouteImport } from './routes/admin/locations'
import { Route as AdminMascotsRouteImport } from './routes/admin/mascots'
import { Route as AdminModerationRouteImport } from './routes/admin/moderation'
import { Route as AdminMyWorkRouteImport } from './routes/admin/my-work'
import { Route as AdminRolesRouteImport } from './routes/admin/roles'
import { Route as AdminSearchRouteImport } from './routes/admin/search'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminStoresRouteImport } from './routes/admin/stores'
import { Route as AdminStudentBotRouteImport } from './routes/admin/student-bot'
import { Route as AdminTaxonomyRouteImport } from './routes/admin/taxonomy'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminVerificationsRouteImport } from './routes/admin/verifications'
import { Route as AdsSlugRouteImport } from './routes/ads.$slug'
import { Route as BusinessIndexRouteImport } from './routes/business/index'
import { Route as BusinessOrdersRouteImport } from './routes/business/orders'
import { Route as BusinessPartnersRouteImport } from './routes/business/partners'
import { Route as BusinessProfileRouteImport } from './routes/business/profile'
import { Route as BusinessesSlugRouteImport } from './routes/businesses.$slug'
import { Route as CategoriesSlugRouteImport } from './routes/categories.$slug'
import { Route as DemoStoresWorldIdRouteImport } from './routes/demo-stores.$worldId'
import { Route as GuidesStudentsRouteImport } from './routes/guides/students'
import { Route as GuidesSyriaRouteImport } from './routes/guides/syria'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as LegalCopyrightRouteImport } from './routes/legal/copyright'
import { Route as LegalTermsRouteImport } from './routes/legal/terms'
import { Route as MyAdCreditRouteImport } from './routes/my/ad-credit'
import { Route as MyBookingsRouteImport } from './routes/my/bookings'
import { Route as MyCaptainRouteImport } from './routes/my/captain'
import { Route as MyFavoritesRouteImport } from './routes/my/favorites'
import { Route as MyMessagesRouteImport } from './routes/my/messages'
import { Route as MyNotificationsRouteImport } from './routes/my/notifications'
import { Route as MyOrdersRouteImport } from './routes/my/orders'
import { Route as MyProfileRouteImport } from './routes/my/profile'
import { Route as MyQuotesRouteImport } from './routes/my/quotes'
import { Route as MyViolationsRouteImport } from './routes/my/violations'
import { Route as MyWalletRouteImport } from './routes/my/wallet'
import { Route as ProfilesUsernameRouteImport } from './routes/profiles.$username'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as StoresSlugRouteImport } from './routes/stores.$slug'
import { Route as AdminBusinessesIdRouteImport } from './routes/admin/businesses_.$id'
import { Route as AdminListingsIdRouteImport } from './routes/admin/listings_.$id'
import { Route as AdminReportsIndexRouteImport } from './routes/admin/reports.index'
import { Route as AdminReportsIdRouteImport } from './routes/admin/reports.$id'
import { Route as AdminStaffAttendanceRouteImport } from './routes/admin/staff.attendance'
import { Route as AdminStaffWorkloadRouteImport } from './routes/admin/staff.workload'
import { Route as AdminUsersIdRouteImport } from './routes/admin/users_.$id'
import { Route as AdminVerificationsIdRouteImport } from './routes/admin/verifications_.$id'
import { Route as ApiPublicKaheelIntroDotpdfRouteImport } from './routes/api/public/kaheel-intro[.]pdf'
import { Route as BusinessServicesIndexRouteImport } from './routes/business/services.index'
import { Route as BusinessServicesSettingsRouteImport } from './routes/business/services.settings'
import { Route as BusinessStoreIndexRouteImport } from './routes/business/store.index'
import { Route as BusinessStoreCatalogRouteImport } from './routes/business/store.catalog'
import { Route as BusinessStoreNewRouteImport } from './routes/business/store.new'
import { Route as BusinessStoreOffersRouteImport } from './routes/business/store.offers'
import { Route as GuidesStudentsAssistantRouteImport } from './routes/guides/students_.assistant'
import { Route as GuidesSyriaSlugRouteImport } from './routes/guides/syria_.$slug'
import { Route as MyAdsIndexRouteImport } from './routes/my/ads.index'
import { Route as MyAdsNewRouteImport } from './routes/my/ads.new'
import { Route as MyErrandsIndexRouteImport } from './routes/my/errands.index'
import { Route as MyErrandsIdRouteImport } from './routes/my/errands.$id'
import { Route as MyReportsIndexRouteImport } from './routes/my/reports.index'
import { Route as MyReportsIdRouteImport } from './routes/my/reports.$id'
import { Route as ApiPublicAdCreditGatewayWebhookRouteImport } from './routes/api/public/ad-credit/gateway-webhook'
import { Route as ApiPublicOtpLinksyriaStatusRouteImport } from './routes/api/public/otp/linksyria-status'
import { Route as MyAdsIdEditRouteImport } from './routes/my/ads.$id.edit'
import { Route as ServicesSlugItemIdBookRouteImport } from './routes/services.$slug.$itemId.book'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessRouteRoute = BusinessRouteRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => rootRouteImport,
} as any)
const ChooseAccountRoute = ChooseAccountRouteImport.update({
  id: '/choose-account',
  path: '/choose-account',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrandsRoute = ErrandsRouteImport.update({
  id: '/errands',
  path: '/errands',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const GoRoute = GoRouteImport.update({
  id: '/go',
  path: '/go',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const KidsRoute = KidsRouteImport.update({
  id: '/kids',
  path: '/kids',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketSetupRoute = MarketSetupRouteImport.update({
  id: '/market-setup',
  path: '/market-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const MoreRoute = MoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => rootRouteImport,
} as any)
const MyRouteRoute = MyRouteRouteImport.update({
  id: '/my',
  path: '/my',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAdCreditRoute = AdminAdCreditRouteImport.update({
  id: '/ad-credit',
  path: '/ad-credit',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminApplicationsRoute = AdminApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAuditLogRoute = AdminAuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminBusinessesRoute = AdminBusinessesRouteImport.update({
  id: '/businesses',
  path: '/businesses',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCampaignsRoute = AdminCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminErrandsRoute = AdminErrandsRouteImport.update({
  id: '/errands',
  path: '/errands',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminGuideQueueRoute = AdminGuideQueueRouteImport.update({
  id: '/guide-queue',
  path: '/guide-queue',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminListingEventsRoute = AdminListingEventsRouteImport.update({
  id: '/listing-events',
  path: '/listing-events',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminListingReportsRoute = AdminListingReportsRouteImport.update({
  id: '/listing-reports',
  path: '/listing-reports',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminListingsRoute = AdminListingsRouteImport.update({
  id: '/listings',
  path: '/listings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLocationsRoute = AdminLocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMascotsRoute = AdminMascotsRouteImport.update({
  id: '/mascots',
  path: '/mascots',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminModerationRoute = AdminModerationRouteImport.update({
  id: '/moderation',
  path: '/moderation',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMyWorkRoute = AdminMyWorkRouteImport.update({
  id: '/my-work',
  path: '/my-work',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminRolesRoute = AdminRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSearchRoute = AdminSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminStoresRoute = AdminStoresRouteImport.update({
  id: '/stores',
  path: '/stores',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminStudentBotRoute = AdminStudentBotRouteImport.update({
  id: '/student-bot',
  path: '/student-bot',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminTaxonomyRoute = AdminTaxonomyRouteImport.update({
  id: '/taxonomy',
  path: '/taxonomy',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminVerificationsRoute = AdminVerificationsRouteImport.update({
  id: '/verifications',
  path: '/verifications',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdsSlugRoute = AdsSlugRouteImport.update({
  id: '/ads/$slug',
  path: '/ads/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessIndexRoute = BusinessIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BusinessRouteRoute,
} as any)
const BusinessOrdersRoute = BusinessOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => BusinessRouteRoute,
} as any)
const BusinessPartnersRoute = BusinessPartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => BusinessRouteRoute,
} as any)
const BusinessProfileRoute = BusinessProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => BusinessRouteRoute,
} as any)
const BusinessesSlugRoute = BusinessesSlugRouteImport.update({
  id: '/businesses/$slug',
  path: '/businesses/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesSlugRoute = CategoriesSlugRouteImport.update({
  id: '/categories/$slug',
  path: '/categories/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStoresWorldIdRoute = DemoStoresWorldIdRouteImport.update({
  id: '/demo-stores/$worldId',
  path: '/demo-stores/$worldId',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesStudentsRoute = GuidesStudentsRouteImport.update({
  id: '/guides/students',
  path: '/guides/students',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesSyriaRoute = GuidesSyriaRouteImport.update({
  id: '/guides/syria',
  path: '/guides/syria',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalCopyrightRoute = LegalCopyrightRouteImport.update({
  id: '/legal/copyright',
  path: '/legal/copyright',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const MyAdCreditRoute = MyAdCreditRouteImport.update({
  id: '/ad-credit',
  path: '/ad-credit',
  getParentRoute: () => MyRouteRoute,
} as any)
const MyBookingsRoute = MyBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => MyRouteRoute,
} as any)
const MyCaptainRoute = MyCaptainRouteImport.update({
  id: '/captain',
  path: '/captain',
  getParentRoute: () => MyRouteRoute,
} as any)
const MyFavoritesRoute = MyFavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => MyRouteRoute,
} as any)
const MyMessagesRoute = MyMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => MyRouteRoute,
} as any)
const MyNotificationsRoute = MyNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => MyRouteRoute,
} as any)
const MyOrdersRoute = MyOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => MyRouteRoute,
} as any)
const MyProfileRoute = MyProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => MyRouteRoute,
} as any)
const MyQuotesRoute = MyQuotesRouteImport.update({
  id: '/quotes',
  path: '/quotes',
  getParentRoute: () => MyRouteRoute,
} as any)
const MyViolationsRoute = MyViolationsRouteImport.update({
  id: '/violations',
  path: '/violations',
  getParentRoute: () => MyRouteRoute,
} as any)
const MyWalletRoute = MyWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => MyRouteRoute,
} as any)
const ProfilesUsernameRoute = ProfilesUsernameRouteImport.update({
  id: '/profiles/$username',
  path: '/profiles/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServicesRoute,
} as any)
const StoresSlugRoute = StoresSlugRouteImport.update({
  id: '/stores/$slug',
  path: '/stores/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBusinessesIdRoute = AdminBusinessesIdRouteImport.update({
  id: '/businesses_/$id',
  path: '/businesses/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminListingsIdRoute = AdminListingsIdRouteImport.update({
  id: '/listings_/$id',
  path: '/listings/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminReportsIndexRoute = AdminReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminReportsIdRoute = AdminReportsIdRouteImport.update({
  id: '/reports/$id',
  path: '/reports/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminStaffAttendanceRoute = AdminStaffAttendanceRouteImport.update({
  id: '/staff/attendance',
  path: '/staff/attendance',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminStaffWorkloadRoute = AdminStaffWorkloadRouteImport.update({
  id: '/staff/workload',
  path: '/staff/workload',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUsersIdRoute = AdminUsersIdRouteImport.update({
  id: '/users_/$id',
  path: '/users/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminVerificationsIdRoute = AdminVerificationsIdRouteImport.update({
  id: '/verifications_/$id',
  path: '/verifications/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ApiPublicKaheelIntroDotpdfRoute =
  ApiPublicKaheelIntroDotpdfRouteImport.update({
    id: '/api/public/kaheel-intro.pdf',
    path: '/api/public/kaheel-intro.pdf',
    getParentRoute: () => rootRouteImport,
  } as any)
const BusinessServicesIndexRoute = BusinessServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => BusinessRouteRoute,
} as any)
const BusinessServicesSettingsRoute =
  BusinessServicesSettingsRouteImport.update({
    id: '/services/settings',
    path: '/services/settings',
    getParentRoute: () => BusinessRouteRoute,
  } as any)
const BusinessStoreIndexRoute = BusinessStoreIndexRouteImport.update({
  id: '/store/',
  path: '/store/',
  getParentRoute: () => BusinessRouteRoute,
} as any)
const BusinessStoreCatalogRoute = BusinessStoreCatalogRouteImport.update({
  id: '/store/catalog',
  path: '/store/catalog',
  getParentRoute: () => BusinessRouteRoute,
} as any)
const BusinessStoreNewRoute = BusinessStoreNewRouteImport.update({
  id: '/store/new',
  path: '/store/new',
  getParentRoute: () => BusinessRouteRoute,
} as any)
const BusinessStoreOffersRoute = BusinessStoreOffersRouteImport.update({
  id: '/store/offers',
  path: '/store/offers',
  getParentRoute: () => BusinessRouteRoute,
} as any)
const GuidesStudentsAssistantRoute = GuidesStudentsAssistantRouteImport.update({
  id: '/guides/students_/assistant',
  path: '/guides/students/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesSyriaSlugRoute = GuidesSyriaSlugRouteImport.update({
  id: '/guides/syria_/$slug',
  path: '/guides/syria/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MyAdsIndexRoute = MyAdsIndexRouteImport.update({
  id: '/ads/',
  path: '/ads/',
  getParentRoute: () => MyRouteRoute,
} as any)
const MyAdsNewRoute = MyAdsNewRouteImport.update({
  id: '/ads/new',
  path: '/ads/new',
  getParentRoute: () => MyRouteRoute,
} as any)
const MyErrandsIndexRoute = MyErrandsIndexRouteImport.update({
  id: '/errands/',
  path: '/errands/',
  getParentRoute: () => MyRouteRoute,
} as any)
const MyErrandsIdRoute = MyErrandsIdRouteImport.update({
  id: '/errands/$id',
  path: '/errands/$id',
  getParentRoute: () => MyRouteRoute,
} as any)
const MyReportsIndexRoute = MyReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => MyRouteRoute,
} as any)
const MyReportsIdRoute = MyReportsIdRouteImport.update({
  id: '/reports/$id',
  path: '/reports/$id',
  getParentRoute: () => MyRouteRoute,
} as any)
const ApiPublicAdCreditGatewayWebhookRoute =
  ApiPublicAdCreditGatewayWebhookRouteImport.update({
    id: '/api/public/ad-credit/gateway-webhook',
    path: '/api/public/ad-credit/gateway-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicOtpLinksyriaStatusRoute =
  ApiPublicOtpLinksyriaStatusRouteImport.update({
    id: '/api/public/otp/linksyria-status',
    path: '/api/public/otp/linksyria-status',
    getParentRoute: () => rootRouteImport,
  } as any)
const MyAdsIdEditRoute = MyAdsIdEditRouteImport.update({
  id: '/ads/$id/edit',
  path: '/ads/$id/edit',
  getParentRoute: () => MyRouteRoute,
} as any)
const ServicesSlugItemIdBookRoute = ServicesSlugItemIdBookRouteImport.update({
  id: '/$slug/$itemId/book',
  path: '/$slug/$itemId/book',
  getParentRoute: () => ServicesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/business': typeof BusinessRouteRouteWithChildren
  '/my': typeof MyRouteRouteWithChildren
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/choose-account': typeof ChooseAccountRoute
  '/demo': typeof DemoRoute
  '/errands': typeof ErrandsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/go': typeof GoRoute
  '/help': typeof HelpRoute
  '/join': typeof JoinRoute
  '/kids': typeof KidsRoute
  '/market-setup': typeof MarketSetupRoute
  '/more': typeof MoreRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/services': typeof ServicesRouteWithChildren
  '/admin/ad-credit': typeof AdminAdCreditRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/audit-log': typeof AdminAuditLogRoute
  '/admin/businesses': typeof AdminBusinessesRoute
  '/admin/campaigns': typeof AdminCampaignsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/errands': typeof AdminErrandsRoute
  '/admin/guide-queue': typeof AdminGuideQueueRoute
  '/admin/listing-events': typeof AdminListingEventsRoute
  '/admin/listing-reports': typeof AdminListingReportsRoute
  '/admin/listings': typeof AdminListingsRoute
  '/admin/locations': typeof AdminLocationsRoute
  '/admin/mascots': typeof AdminMascotsRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/my-work': typeof AdminMyWorkRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/search': typeof AdminSearchRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/stores': typeof AdminStoresRoute
  '/admin/student-bot': typeof AdminStudentBotRoute
  '/admin/taxonomy': typeof AdminTaxonomyRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/verifications': typeof AdminVerificationsRoute
  '/ads/$slug': typeof AdsSlugRoute
  '/business/orders': typeof BusinessOrdersRoute
  '/business/partners': typeof BusinessPartnersRoute
  '/business/profile': typeof BusinessProfileRoute
  '/businesses/$slug': typeof BusinessesSlugRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/demo-stores/$worldId': typeof DemoStoresWorldIdRoute
  '/guides/students': typeof GuidesStudentsRoute
  '/guides/syria': typeof GuidesSyriaRoute
  '/invite/$token': typeof InviteTokenRoute
  '/legal/copyright': typeof LegalCopyrightRoute
  '/legal/terms': typeof LegalTermsRoute
  '/my/ad-credit': typeof MyAdCreditRoute
  '/my/bookings': typeof MyBookingsRoute
  '/my/captain': typeof MyCaptainRoute
  '/my/favorites': typeof MyFavoritesRoute
  '/my/messages': typeof MyMessagesRoute
  '/my/notifications': typeof MyNotificationsRoute
  '/my/orders': typeof MyOrdersRoute
  '/my/profile': typeof MyProfileRoute
  '/my/quotes': typeof MyQuotesRoute
  '/my/violations': typeof MyViolationsRoute
  '/my/wallet': typeof MyWalletRoute
  '/profiles/$username': typeof ProfilesUsernameRoute
  '/stores/$slug': typeof StoresSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/business/': typeof BusinessIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/admin/businesses/$id': typeof AdminBusinessesIdRoute
  '/admin/listings/$id': typeof AdminListingsIdRoute
  '/admin/reports/$id': typeof AdminReportsIdRoute
  '/admin/staff/attendance': typeof AdminStaffAttendanceRoute
  '/admin/staff/workload': typeof AdminStaffWorkloadRoute
  '/admin/users/$id': typeof AdminUsersIdRoute
  '/admin/verifications/$id': typeof AdminVerificationsIdRoute
  '/api/public/kaheel-intro.pdf': typeof ApiPublicKaheelIntroDotpdfRoute
  '/business/services/settings': typeof BusinessServicesSettingsRoute
  '/business/store/catalog': typeof BusinessStoreCatalogRoute
  '/business/store/new': typeof BusinessStoreNewRoute
  '/business/store/offers': typeof BusinessStoreOffersRoute
  '/guides/students/assistant': typeof GuidesStudentsAssistantRoute
  '/guides/syria/$slug': typeof GuidesSyriaSlugRoute
  '/my/ads/new': typeof MyAdsNewRoute
  '/my/errands/$id': typeof MyErrandsIdRoute
  '/my/reports/$id': typeof MyReportsIdRoute
  '/admin/reports/': typeof AdminReportsIndexRoute
  '/business/services/': typeof BusinessServicesIndexRoute
  '/business/store/': typeof BusinessStoreIndexRoute
  '/my/ads/': typeof MyAdsIndexRoute
  '/my/errands/': typeof MyErrandsIndexRoute
  '/my/reports/': typeof MyReportsIndexRoute
  '/api/public/ad-credit/gateway-webhook': typeof ApiPublicAdCreditGatewayWebhookRoute
  '/api/public/otp/linksyria-status': typeof ApiPublicOtpLinksyriaStatusRoute
  '/my/ads/$id/edit': typeof MyAdsIdEditRoute
  '/services/$slug/$itemId/book': typeof ServicesSlugItemIdBookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/my': typeof MyRouteRouteWithChildren
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/choose-account': typeof ChooseAccountRoute
  '/demo': typeof DemoRoute
  '/errands': typeof ErrandsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/go': typeof GoRoute
  '/help': typeof HelpRoute
  '/join': typeof JoinRoute
  '/kids': typeof KidsRoute
  '/market-setup': typeof MarketSetupRoute
  '/more': typeof MoreRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/admin/ad-credit': typeof AdminAdCreditRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/audit-log': typeof AdminAuditLogRoute
  '/admin/businesses': typeof AdminBusinessesRoute
  '/admin/campaigns': typeof AdminCampaignsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/errands': typeof AdminErrandsRoute
  '/admin/guide-queue': typeof AdminGuideQueueRoute
  '/admin/listing-events': typeof AdminListingEventsRoute
  '/admin/listing-reports': typeof AdminListingReportsRoute
  '/admin/listings': typeof AdminListingsRoute
  '/admin/locations': typeof AdminLocationsRoute
  '/admin/mascots': typeof AdminMascotsRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/my-work': typeof AdminMyWorkRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/search': typeof AdminSearchRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/stores': typeof AdminStoresRoute
  '/admin/student-bot': typeof AdminStudentBotRoute
  '/admin/taxonomy': typeof AdminTaxonomyRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/verifications': typeof AdminVerificationsRoute
  '/ads/$slug': typeof AdsSlugRoute
  '/business/orders': typeof BusinessOrdersRoute
  '/business/partners': typeof BusinessPartnersRoute
  '/business/profile': typeof BusinessProfileRoute
  '/businesses/$slug': typeof BusinessesSlugRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/demo-stores/$worldId': typeof DemoStoresWorldIdRoute
  '/guides/students': typeof GuidesStudentsRoute
  '/guides/syria': typeof GuidesSyriaRoute
  '/invite/$token': typeof InviteTokenRoute
  '/legal/copyright': typeof LegalCopyrightRoute
  '/legal/terms': typeof LegalTermsRoute
  '/my/ad-credit': typeof MyAdCreditRoute
  '/my/bookings': typeof MyBookingsRoute
  '/my/captain': typeof MyCaptainRoute
  '/my/favorites': typeof MyFavoritesRoute
  '/my/messages': typeof MyMessagesRoute
  '/my/notifications': typeof MyNotificationsRoute
  '/my/orders': typeof MyOrdersRoute
  '/my/profile': typeof MyProfileRoute
  '/my/quotes': typeof MyQuotesRoute
  '/my/violations': typeof MyViolationsRoute
  '/my/wallet': typeof MyWalletRoute
  '/profiles/$username': typeof ProfilesUsernameRoute
  '/stores/$slug': typeof StoresSlugRoute
  '/admin': typeof AdminIndexRoute
  '/business': typeof BusinessIndexRoute
  '/services': typeof ServicesIndexRoute
  '/admin/businesses/$id': typeof AdminBusinessesIdRoute
  '/admin/listings/$id': typeof AdminListingsIdRoute
  '/admin/reports/$id': typeof AdminReportsIdRoute
  '/admin/staff/attendance': typeof AdminStaffAttendanceRoute
  '/admin/staff/workload': typeof AdminStaffWorkloadRoute
  '/admin/users/$id': typeof AdminUsersIdRoute
  '/admin/verifications/$id': typeof AdminVerificationsIdRoute
  '/api/public/kaheel-intro.pdf': typeof ApiPublicKaheelIntroDotpdfRoute
  '/business/services/settings': typeof BusinessServicesSettingsRoute
  '/business/store/catalog': typeof BusinessStoreCatalogRoute
  '/business/store/new': typeof BusinessStoreNewRoute
  '/business/store/offers': typeof BusinessStoreOffersRoute
  '/guides/students/assistant': typeof GuidesStudentsAssistantRoute
  '/guides/syria/$slug': typeof GuidesSyriaSlugRoute
  '/my/ads/new': typeof MyAdsNewRoute
  '/my/errands/$id': typeof MyErrandsIdRoute
  '/my/reports/$id': typeof MyReportsIdRoute
  '/admin/reports': typeof AdminReportsIndexRoute
  '/business/services': typeof BusinessServicesIndexRoute
  '/business/store': typeof BusinessStoreIndexRoute
  '/my/ads': typeof MyAdsIndexRoute
  '/my/errands': typeof MyErrandsIndexRoute
  '/my/reports': typeof MyReportsIndexRoute
  '/api/public/ad-credit/gateway-webhook': typeof ApiPublicAdCreditGatewayWebhookRoute
  '/api/public/otp/linksyria-status': typeof ApiPublicOtpLinksyriaStatusRoute
  '/my/ads/$id/edit': typeof MyAdsIdEditRoute
  '/services/$slug/$itemId/book': typeof ServicesSlugItemIdBookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/business': typeof BusinessRouteRouteWithChildren
  '/my': typeof MyRouteRouteWithChildren
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/choose-account': typeof ChooseAccountRoute
  '/demo': typeof DemoRoute
  '/errands': typeof ErrandsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/go': typeof GoRoute
  '/help': typeof HelpRoute
  '/join': typeof JoinRoute
  '/kids': typeof KidsRoute
  '/market-setup': typeof MarketSetupRoute
  '/more': typeof MoreRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/services': typeof ServicesRouteWithChildren
  '/admin/ad-credit': typeof AdminAdCreditRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/audit-log': typeof AdminAuditLogRoute
  '/admin/businesses': typeof AdminBusinessesRoute
  '/admin/campaigns': typeof AdminCampaignsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/errands': typeof AdminErrandsRoute
  '/admin/guide-queue': typeof AdminGuideQueueRoute
  '/admin/listing-events': typeof AdminListingEventsRoute
  '/admin/listing-reports': typeof AdminListingReportsRoute
  '/admin/listings': typeof AdminListingsRoute
  '/admin/locations': typeof AdminLocationsRoute
  '/admin/mascots': typeof AdminMascotsRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/my-work': typeof AdminMyWorkRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/search': typeof AdminSearchRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/stores': typeof AdminStoresRoute
  '/admin/student-bot': typeof AdminStudentBotRoute
  '/admin/taxonomy': typeof AdminTaxonomyRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/verifications': typeof AdminVerificationsRoute
  '/ads/$slug': typeof AdsSlugRoute
  '/business/orders': typeof BusinessOrdersRoute
  '/business/partners': typeof BusinessPartnersRoute
  '/business/profile': typeof BusinessProfileRoute
  '/businesses/$slug': typeof BusinessesSlugRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/demo-stores/$worldId': typeof DemoStoresWorldIdRoute
  '/guides/students': typeof GuidesStudentsRoute
  '/guides/syria': typeof GuidesSyriaRoute
  '/invite/$token': typeof InviteTokenRoute
  '/legal/copyright': typeof LegalCopyrightRoute
  '/legal/terms': typeof LegalTermsRoute
  '/my/ad-credit': typeof MyAdCreditRoute
  '/my/bookings': typeof MyBookingsRoute
  '/my/captain': typeof MyCaptainRoute
  '/my/favorites': typeof MyFavoritesRoute
  '/my/messages': typeof MyMessagesRoute
  '/my/notifications': typeof MyNotificationsRoute
  '/my/orders': typeof MyOrdersRoute
  '/my/profile': typeof MyProfileRoute
  '/my/quotes': typeof MyQuotesRoute
  '/my/violations': typeof MyViolationsRoute
  '/my/wallet': typeof MyWalletRoute
  '/profiles/$username': typeof ProfilesUsernameRoute
  '/stores/$slug': typeof StoresSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/business/': typeof BusinessIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/admin/businesses_/$id': typeof AdminBusinessesIdRoute
  '/admin/listings_/$id': typeof AdminListingsIdRoute
  '/admin/reports/$id': typeof AdminReportsIdRoute
  '/admin/staff/attendance': typeof AdminStaffAttendanceRoute
  '/admin/staff/workload': typeof AdminStaffWorkloadRoute
  '/admin/users_/$id': typeof AdminUsersIdRoute
  '/admin/verifications_/$id': typeof AdminVerificationsIdRoute
  '/api/public/kaheel-intro.pdf': typeof ApiPublicKaheelIntroDotpdfRoute
  '/business/services/settings': typeof BusinessServicesSettingsRoute
  '/business/store/catalog': typeof BusinessStoreCatalogRoute
  '/business/store/new': typeof BusinessStoreNewRoute
  '/business/store/offers': typeof BusinessStoreOffersRoute
  '/guides/students_/assistant': typeof GuidesStudentsAssistantRoute
  '/guides/syria_/$slug': typeof GuidesSyriaSlugRoute
  '/my/ads/new': typeof MyAdsNewRoute
  '/my/errands/$id': typeof MyErrandsIdRoute
  '/my/reports/$id': typeof MyReportsIdRoute
  '/admin/reports/': typeof AdminReportsIndexRoute
  '/business/services/': typeof BusinessServicesIndexRoute
  '/business/store/': typeof BusinessStoreIndexRoute
  '/my/ads/': typeof MyAdsIndexRoute
  '/my/errands/': typeof MyErrandsIndexRoute
  '/my/reports/': typeof MyReportsIndexRoute
  '/api/public/ad-credit/gateway-webhook': typeof ApiPublicAdCreditGatewayWebhookRoute
  '/api/public/otp/linksyria-status': typeof ApiPublicOtpLinksyriaStatusRoute
  '/my/ads/$id/edit': typeof MyAdsIdEditRoute
  '/services/$slug/$itemId/book': typeof ServicesSlugItemIdBookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/business'
    | '/my'
    | '/$'
    | '/about'
    | '/auth'
    | '/choose-account'
    | '/demo'
    | '/errands'
    | '/forgot-password'
    | '/go'
    | '/help'
    | '/join'
    | '/kids'
    | '/market-setup'
    | '/more'
    | '/register'
    | '/reset-password'
    | '/search'
    | '/services'
    | '/admin/ad-credit'
    | '/admin/applications'
    | '/admin/audit-log'
    | '/admin/businesses'
    | '/admin/campaigns'
    | '/admin/dashboard'
    | '/admin/errands'
    | '/admin/guide-queue'
    | '/admin/listing-events'
    | '/admin/listing-reports'
    | '/admin/listings'
    | '/admin/locations'
    | '/admin/mascots'
    | '/admin/moderation'
    | '/admin/my-work'
    | '/admin/roles'
    | '/admin/search'
    | '/admin/settings'
    | '/admin/stores'
    | '/admin/student-bot'
    | '/admin/taxonomy'
    | '/admin/users'
    | '/admin/verifications'
    | '/ads/$slug'
    | '/business/orders'
    | '/business/partners'
    | '/business/profile'
    | '/businesses/$slug'
    | '/categories/$slug'
    | '/demo-stores/$worldId'
    | '/guides/students'
    | '/guides/syria'
    | '/invite/$token'
    | '/legal/copyright'
    | '/legal/terms'
    | '/my/ad-credit'
    | '/my/bookings'
    | '/my/captain'
    | '/my/favorites'
    | '/my/messages'
    | '/my/notifications'
    | '/my/orders'
    | '/my/profile'
    | '/my/quotes'
    | '/my/violations'
    | '/my/wallet'
    | '/profiles/$username'
    | '/stores/$slug'
    | '/admin/'
    | '/business/'
    | '/services/'
    | '/admin/businesses/$id'
    | '/admin/listings/$id'
    | '/admin/reports/$id'
    | '/admin/staff/attendance'
    | '/admin/staff/workload'
    | '/admin/users/$id'
    | '/admin/verifications/$id'
    | '/api/public/kaheel-intro.pdf'
    | '/business/services/settings'
    | '/business/store/catalog'
    | '/business/store/new'
    | '/business/store/offers'
    | '/guides/students/assistant'
    | '/guides/syria/$slug'
    | '/my/ads/new'
    | '/my/errands/$id'
    | '/my/reports/$id'
    | '/admin/reports/'
    | '/business/services/'
    | '/business/store/'
    | '/my/ads/'
    | '/my/errands/'
    | '/my/reports/'
    | '/api/public/ad-credit/gateway-webhook'
    | '/api/public/otp/linksyria-status'
    | '/my/ads/$id/edit'
    | '/services/$slug/$itemId/book'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/my'
    | '/$'
    | '/about'
    | '/auth'
    | '/choose-account'
    | '/demo'
    | '/errands'
    | '/forgot-password'
    | '/go'
    | '/help'
    | '/join'
    | '/kids'
    | '/market-setup'
    | '/more'
    | '/register'
    | '/reset-password'
    | '/search'
    | '/admin/ad-credit'
    | '/admin/applications'
    | '/admin/audit-log'
    | '/admin/businesses'
    | '/admin/campaigns'
    | '/admin/dashboard'
    | '/admin/errands'
    | '/admin/guide-queue'
    | '/admin/listing-events'
    | '/admin/listing-reports'
    | '/admin/listings'
    | '/admin/locations'
    | '/admin/mascots'
    | '/admin/moderation'
    | '/admin/my-work'
    | '/admin/roles'
    | '/admin/search'
    | '/admin/settings'
    | '/admin/stores'
    | '/admin/student-bot'
    | '/admin/taxonomy'
    | '/admin/users'
    | '/admin/verifications'
    | '/ads/$slug'
    | '/business/orders'
    | '/business/partners'
    | '/business/profile'
    | '/businesses/$slug'
    | '/categories/$slug'
    | '/demo-stores/$worldId'
    | '/guides/students'
    | '/guides/syria'
    | '/invite/$token'
    | '/legal/copyright'
    | '/legal/terms'
    | '/my/ad-credit'
    | '/my/bookings'
    | '/my/captain'
    | '/my/favorites'
    | '/my/messages'
    | '/my/notifications'
    | '/my/orders'
    | '/my/profile'
    | '/my/quotes'
    | '/my/violations'
    | '/my/wallet'
    | '/profiles/$username'
    | '/stores/$slug'
    | '/admin'
    | '/business'
    | '/services'
    | '/admin/businesses/$id'
    | '/admin/listings/$id'
    | '/admin/reports/$id'
    | '/admin/staff/attendance'
    | '/admin/staff/workload'
    | '/admin/users/$id'
    | '/admin/verifications/$id'
    | '/api/public/kaheel-intro.pdf'
    | '/business/services/settings'
    | '/business/store/catalog'
    | '/business/store/new'
    | '/business/store/offers'
    | '/guides/students/assistant'
    | '/guides/syria/$slug'
    | '/my/ads/new'
    | '/my/errands/$id'
    | '/my/reports/$id'
    | '/admin/reports'
    | '/business/services'
    | '/business/store'
    | '/my/ads'
    | '/my/errands'
    | '/my/reports'
    | '/api/public/ad-credit/gateway-webhook'
    | '/api/public/otp/linksyria-status'
    | '/my/ads/$id/edit'
    | '/services/$slug/$itemId/book'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/business'
    | '/my'
    | '/$'
    | '/about'
    | '/auth'
    | '/choose-account'
    | '/demo'
    | '/errands'
    | '/forgot-password'
    | '/go'
    | '/help'
    | '/join'
    | '/kids'
    | '/market-setup'
    | '/more'
    | '/register'
    | '/reset-password'
    | '/search'
    | '/services'
    | '/admin/ad-credit'
    | '/admin/applications'
    | '/admin/audit-log'
    | '/admin/businesses'
    | '/admin/campaigns'
    | '/admin/dashboard'
    | '/admin/errands'
    | '/admin/guide-queue'
    | '/admin/listing-events'
    | '/admin/listing-reports'
    | '/admin/listings'
    | '/admin/locations'
    | '/admin/mascots'
    | '/admin/moderation'
    | '/admin/my-work'
    | '/admin/roles'
    | '/admin/search'
    | '/admin/settings'
    | '/admin/stores'
    | '/admin/student-bot'
    | '/admin/taxonomy'
    | '/admin/users'
    | '/admin/verifications'
    | '/ads/$slug'
    | '/business/orders'
    | '/business/partners'
    | '/business/profile'
    | '/businesses/$slug'
    | '/categories/$slug'
    | '/demo-stores/$worldId'
    | '/guides/students'
    | '/guides/syria'
    | '/invite/$token'
    | '/legal/copyright'
    | '/legal/terms'
    | '/my/ad-credit'
    | '/my/bookings'
    | '/my/captain'
    | '/my/favorites'
    | '/my/messages'
    | '/my/notifications'
    | '/my/orders'
    | '/my/profile'
    | '/my/quotes'
    | '/my/violations'
    | '/my/wallet'
    | '/profiles/$username'
    | '/stores/$slug'
    | '/admin/'
    | '/business/'
    | '/services/'
    | '/admin/businesses_/$id'
    | '/admin/listings_/$id'
    | '/admin/reports/$id'
    | '/admin/staff/attendance'
    | '/admin/staff/workload'
    | '/admin/users_/$id'
    | '/admin/verifications_/$id'
    | '/api/public/kaheel-intro.pdf'
    | '/business/services/settings'
    | '/business/store/catalog'
    | '/business/store/new'
    | '/business/store/offers'
    | '/guides/students_/assistant'
    | '/guides/syria_/$slug'
    | '/my/ads/new'
    | '/my/errands/$id'
    | '/my/reports/$id'
    | '/admin/reports/'
    | '/business/services/'
    | '/business/store/'
    | '/my/ads/'
    | '/my/errands/'
    | '/my/reports/'
    | '/api/public/ad-credit/gateway-webhook'
    | '/api/public/otp/linksyria-status'
    | '/my/ads/$id/edit'
    | '/services/$slug/$itemId/book'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  BusinessRouteRoute: typeof BusinessRouteRouteWithChildren
  MyRouteRoute: typeof MyRouteRouteWithChildren
  SplatRoute: typeof SplatRoute
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  ChooseAccountRoute: typeof ChooseAccountRoute
  DemoRoute: typeof DemoRoute
  ErrandsRoute: typeof ErrandsRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  GoRoute: typeof GoRoute
  HelpRoute: typeof HelpRoute
  JoinRoute: typeof JoinRoute
  KidsRoute: typeof KidsRoute
  MarketSetupRoute: typeof MarketSetupRoute
  MoreRoute: typeof MoreRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SearchRoute: typeof SearchRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  AdsSlugRoute: typeof AdsSlugRoute
  BusinessesSlugRoute: typeof BusinessesSlugRoute
  CategoriesSlugRoute: typeof CategoriesSlugRoute
  DemoStoresWorldIdRoute: typeof DemoStoresWorldIdRoute
  GuidesStudentsRoute: typeof GuidesStudentsRoute
  GuidesSyriaRoute: typeof GuidesSyriaRoute
  InviteTokenRoute: typeof InviteTokenRoute
  LegalCopyrightRoute: typeof LegalCopyrightRoute
  LegalTermsRoute: typeof LegalTermsRoute
  ProfilesUsernameRoute: typeof ProfilesUsernameRoute
  StoresSlugRoute: typeof StoresSlugRoute
  ApiPublicKaheelIntroDotpdfRoute: typeof ApiPublicKaheelIntroDotpdfRoute
  GuidesStudentsAssistantRoute: typeof GuidesStudentsAssistantRoute
  GuidesSyriaSlugRoute: typeof GuidesSyriaSlugRoute
  ApiPublicAdCreditGatewayWebhookRoute: typeof ApiPublicAdCreditGatewayWebhookRoute
  ApiPublicOtpLinksyriaStatusRoute: typeof ApiPublicOtpLinksyriaStatusRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business': {
      id: '/business'
      path: '/business'
      fullPath: '/business'
      preLoaderRoute: typeof BusinessRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/choose-account': {
      id: '/choose-account'
      path: '/choose-account'
      fullPath: '/choose-account'
      preLoaderRoute: typeof ChooseAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/errands': {
      id: '/errands'
      path: '/errands'
      fullPath: '/errands'
      preLoaderRoute: typeof ErrandsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/go': {
      id: '/go'
      path: '/go'
      fullPath: '/go'
      preLoaderRoute: typeof GoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kids': {
      id: '/kids'
      path: '/kids'
      fullPath: '/kids'
      preLoaderRoute: typeof KidsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market-setup': {
      id: '/market-setup'
      path: '/market-setup'
      fullPath: '/market-setup'
      preLoaderRoute: typeof MarketSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/more': {
      id: '/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof MoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my': {
      id: '/my'
      path: '/my'
      fullPath: '/my'
      preLoaderRoute: typeof MyRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/ad-credit': {
      id: '/admin/ad-credit'
      path: '/ad-credit'
      fullPath: '/admin/ad-credit'
      preLoaderRoute: typeof AdminAdCreditRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/applications': {
      id: '/admin/applications'
      path: '/applications'
      fullPath: '/admin/applications'
      preLoaderRoute: typeof AdminApplicationsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/audit-log': {
      id: '/admin/audit-log'
      path: '/audit-log'
      fullPath: '/admin/audit-log'
      preLoaderRoute: typeof AdminAuditLogRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/businesses': {
      id: '/admin/businesses'
      path: '/businesses'
      fullPath: '/admin/businesses'
      preLoaderRoute: typeof AdminBusinessesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/campaigns': {
      id: '/admin/campaigns'
      path: '/campaigns'
      fullPath: '/admin/campaigns'
      preLoaderRoute: typeof AdminCampaignsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/errands': {
      id: '/admin/errands'
      path: '/errands'
      fullPath: '/admin/errands'
      preLoaderRoute: typeof AdminErrandsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/guide-queue': {
      id: '/admin/guide-queue'
      path: '/guide-queue'
      fullPath: '/admin/guide-queue'
      preLoaderRoute: typeof AdminGuideQueueRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/listing-events': {
      id: '/admin/listing-events'
      path: '/listing-events'
      fullPath: '/admin/listing-events'
      preLoaderRoute: typeof AdminListingEventsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/listing-reports': {
      id: '/admin/listing-reports'
      path: '/listing-reports'
      fullPath: '/admin/listing-reports'
      preLoaderRoute: typeof AdminListingReportsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/listings': {
      id: '/admin/listings'
      path: '/listings'
      fullPath: '/admin/listings'
      preLoaderRoute: typeof AdminListingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/locations': {
      id: '/admin/locations'
      path: '/locations'
      fullPath: '/admin/locations'
      preLoaderRoute: typeof AdminLocationsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/mascots': {
      id: '/admin/mascots'
      path: '/mascots'
      fullPath: '/admin/mascots'
      preLoaderRoute: typeof AdminMascotsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/moderation': {
      id: '/admin/moderation'
      path: '/moderation'
      fullPath: '/admin/moderation'
      preLoaderRoute: typeof AdminModerationRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/my-work': {
      id: '/admin/my-work'
      path: '/my-work'
      fullPath: '/admin/my-work'
      preLoaderRoute: typeof AdminMyWorkRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/roles': {
      id: '/admin/roles'
      path: '/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminRolesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/search': {
      id: '/admin/search'
      path: '/search'
      fullPath: '/admin/search'
      preLoaderRoute: typeof AdminSearchRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/stores': {
      id: '/admin/stores'
      path: '/stores'
      fullPath: '/admin/stores'
      preLoaderRoute: typeof AdminStoresRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/student-bot': {
      id: '/admin/student-bot'
      path: '/student-bot'
      fullPath: '/admin/student-bot'
      preLoaderRoute: typeof AdminStudentBotRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/taxonomy': {
      id: '/admin/taxonomy'
      path: '/taxonomy'
      fullPath: '/admin/taxonomy'
      preLoaderRoute: typeof AdminTaxonomyRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/verifications': {
      id: '/admin/verifications'
      path: '/verifications'
      fullPath: '/admin/verifications'
      preLoaderRoute: typeof AdminVerificationsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/ads/$slug': {
      id: '/ads/$slug'
      path: '/ads/$slug'
      fullPath: '/ads/$slug'
      preLoaderRoute: typeof AdsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/': {
      id: '/business/'
      path: '/'
      fullPath: '/business/'
      preLoaderRoute: typeof BusinessIndexRouteImport
      parentRoute: typeof BusinessRouteRoute
    }
    '/business/orders': {
      id: '/business/orders'
      path: '/orders'
      fullPath: '/business/orders'
      preLoaderRoute: typeof BusinessOrdersRouteImport
      parentRoute: typeof BusinessRouteRoute
    }
    '/business/partners': {
      id: '/business/partners'
      path: '/partners'
      fullPath: '/business/partners'
      preLoaderRoute: typeof BusinessPartnersRouteImport
      parentRoute: typeof BusinessRouteRoute
    }
    '/business/profile': {
      id: '/business/profile'
      path: '/profile'
      fullPath: '/business/profile'
      preLoaderRoute: typeof BusinessProfileRouteImport
      parentRoute: typeof BusinessRouteRoute
    }
    '/businesses/$slug': {
      id: '/businesses/$slug'
      path: '/businesses/$slug'
      fullPath: '/businesses/$slug'
      preLoaderRoute: typeof BusinessesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/$slug': {
      id: '/categories/$slug'
      path: '/categories/$slug'
      fullPath: '/categories/$slug'
      preLoaderRoute: typeof CategoriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo-stores/$worldId': {
      id: '/demo-stores/$worldId'
      path: '/demo-stores/$worldId'
      fullPath: '/demo-stores/$worldId'
      preLoaderRoute: typeof DemoStoresWorldIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/students': {
      id: '/guides/students'
      path: '/guides/students'
      fullPath: '/guides/students'
      preLoaderRoute: typeof GuidesStudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/syria': {
      id: '/guides/syria'
      path: '/guides/syria'
      fullPath: '/guides/syria'
      preLoaderRoute: typeof GuidesSyriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/copyright': {
      id: '/legal/copyright'
      path: '/legal/copyright'
      fullPath: '/legal/copyright'
      preLoaderRoute: typeof LegalCopyrightRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my/ad-credit': {
      id: '/my/ad-credit'
      path: '/ad-credit'
      fullPath: '/my/ad-credit'
      preLoaderRoute: typeof MyAdCreditRouteImport
      parentRoute: typeof MyRouteRoute
    }
    '/my/bookings': {
      id: '/my/bookings'
      path: '/bookings'
      fullPath: '/my/bookings'
      preLoaderRoute: typeof MyBookingsRouteImport
      parentRoute: typeof MyRouteRoute
    }
    '/my/captain': {
      id: '/my/captain'
      path: '/captain'
      fullPath: '/my/captain'
      preLoaderRoute: typeof MyCaptainRouteImport
      parentRoute: typeof MyRouteRoute
    }
    '/my/favorites': {
      id: '/my/favorites'
      path: '/favorites'
      fullPath: '/my/favorites'
      preLoaderRoute: typeof MyFavoritesRouteImport
      parentRoute: typeof MyRouteRoute
    }
    '/my/messages': {
      id: '/my/messages'
      path: '/messages'
      fullPath: '/my/messages'
      preLoaderRoute: typeof MyMessagesRouteImport
      parentRoute: typeof MyRouteRoute
    }
    '/my/notifications': {
      id: '/my/notifications'
      path: '/notifications'
      fullPath: '/my/notifications'
      preLoaderRoute: typeof MyNotificationsRouteImport
      parentRoute: typeof MyRouteRoute
    }
    '/my/orders': {
      id: '/my/orders'
      path: '/orders'
      fullPath: '/my/orders'
      preLoaderRoute: typeof MyOrdersRouteImport
      parentRoute: typeof MyRouteRoute
    }
    '/my/profile': {
      id: '/my/profile'
      path: '/profile'
      fullPath: '/my/profile'
      preLoaderRoute: typeof MyProfileRouteImport
      parentRoute: typeof MyRouteRoute
    }
    '/my/quotes': {
      id: '/my/quotes'
      path: '/quotes'
      fullPath: '/my/quotes'
      preLoaderRoute: typeof MyQuotesRouteImport
      parentRoute: typeof MyRouteRoute
    }
    '/my/violations': {
      id: '/my/violations'
      path: '/violations'
      fullPath: '/my/violations'
      preLoaderRoute: typeof MyViolationsRouteImport
      parentRoute: typeof MyRouteRoute
    }
    '/my/wallet': {
      id: '/my/wallet'
      path: '/wallet'
      fullPath: '/my/wallet'
      preLoaderRoute: typeof MyWalletRouteImport
      parentRoute: typeof MyRouteRoute
    }
    '/profiles/$username': {
      id: '/profiles/$username'
      path: '/profiles/$username'
      fullPath: '/profiles/$username'
      preLoaderRoute: typeof ProfilesUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/stores/$slug': {
      id: '/stores/$slug'
      path: '/stores/$slug'
      fullPath: '/stores/$slug'
      preLoaderRoute: typeof StoresSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/businesses_/$id': {
      id: '/admin/businesses_/$id'
      path: '/businesses/$id'
      fullPath: '/admin/businesses/$id'
      preLoaderRoute: typeof AdminBusinessesIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/listings_/$id': {
      id: '/admin/listings_/$id'
      path: '/listings/$id'
      fullPath: '/admin/listings/$id'
      preLoaderRoute: typeof AdminListingsIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/reports/': {
      id: '/admin/reports/'
      path: '/reports'
      fullPath: '/admin/reports/'
      preLoaderRoute: typeof AdminReportsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/reports/$id': {
      id: '/admin/reports/$id'
      path: '/reports/$id'
      fullPath: '/admin/reports/$id'
      preLoaderRoute: typeof AdminReportsIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/staff/attendance': {
      id: '/admin/staff/attendance'
      path: '/staff/attendance'
      fullPath: '/admin/staff/attendance'
      preLoaderRoute: typeof AdminStaffAttendanceRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/staff/workload': {
      id: '/admin/staff/workload'
      path: '/staff/workload'
      fullPath: '/admin/staff/workload'
      preLoaderRoute: typeof AdminStaffWorkloadRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/users_/$id': {
      id: '/admin/users_/$id'
      path: '/users/$id'
      fullPath: '/admin/users/$id'
      preLoaderRoute: typeof AdminUsersIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/verifications_/$id': {
      id: '/admin/verifications_/$id'
      path: '/verifications/$id'
      fullPath: '/admin/verifications/$id'
      preLoaderRoute: typeof AdminVerificationsIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/api/public/kaheel-intro.pdf': {
      id: '/api/public/kaheel-intro.pdf'
      path: '/api/public/kaheel-intro.pdf'
      fullPath: '/api/public/kaheel-intro.pdf'
      preLoaderRoute: typeof ApiPublicKaheelIntroDotpdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/services/': {
      id: '/business/services/'
      path: '/services'
      fullPath: '/business/services/'
      preLoaderRoute: typeof BusinessServicesIndexRouteImport
      parentRoute: typeof BusinessRouteRoute
    }
    '/business/services/settings': {
      id: '/business/services/settings'
      path: '/services/settings'
      fullPath: '/business/services/settings'
      preLoaderRoute: typeof BusinessServicesSettingsRouteImport
      parentRoute: typeof BusinessRouteRoute
    }
    '/business/store/': {
      id: '/business/store/'
      path: '/store'
      fullPath: '/business/store/'
      preLoaderRoute: typeof BusinessStoreIndexRouteImport
      parentRoute: typeof BusinessRouteRoute
    }
    '/business/store/catalog': {
      id: '/business/store/catalog'
      path: '/store/catalog'
      fullPath: '/business/store/catalog'
      preLoaderRoute: typeof BusinessStoreCatalogRouteImport
      parentRoute: typeof BusinessRouteRoute
    }
    '/business/store/new': {
      id: '/business/store/new'
      path: '/store/new'
      fullPath: '/business/store/new'
      preLoaderRoute: typeof BusinessStoreNewRouteImport
      parentRoute: typeof BusinessRouteRoute
    }
    '/business/store/offers': {
      id: '/business/store/offers'
      path: '/store/offers'
      fullPath: '/business/store/offers'
      preLoaderRoute: typeof BusinessStoreOffersRouteImport
      parentRoute: typeof BusinessRouteRoute
    }
    '/guides/students_/assistant': {
      id: '/guides/students_/assistant'
      path: '/guides/students/assistant'
      fullPath: '/guides/students/assistant'
      preLoaderRoute: typeof GuidesStudentsAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/syria_/$slug': {
      id: '/guides/syria_/$slug'
      path: '/guides/syria/$slug'
      fullPath: '/guides/syria/$slug'
      preLoaderRoute: typeof GuidesSyriaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my/ads/': {
      id: '/my/ads/'
      path: '/ads'
      fullPath: '/my/ads/'
      preLoaderRoute: typeof MyAdsIndexRouteImport
      parentRoute: typeof MyRouteRoute
    }
    '/my/ads/new': {
      id: '/my/ads/new'
      path: '/ads/new'
      fullPath: '/my/ads/new'
      preLoaderRoute: typeof MyAdsNewRouteImport
      parentRoute: typeof MyRouteRoute
    }
    '/my/errands/': {
      id: '/my/errands/'
      path: '/errands'
      fullPath: '/my/errands/'
      preLoaderRoute: typeof MyErrandsIndexRouteImport
      parentRoute: typeof MyRouteRoute
    }
    '/my/errands/$id': {
      id: '/my/errands/$id'
      path: '/errands/$id'
      fullPath: '/my/errands/$id'
      preLoaderRoute: typeof MyErrandsIdRouteImport
      parentRoute: typeof MyRouteRoute
    }
    '/my/reports/': {
      id: '/my/reports/'
      path: '/reports'
      fullPath: '/my/reports/'
      preLoaderRoute: typeof MyReportsIndexRouteImport
      parentRoute: typeof MyRouteRoute
    }
    '/my/reports/$id': {
      id: '/my/reports/$id'
      path: '/reports/$id'
      fullPath: '/my/reports/$id'
      preLoaderRoute: typeof MyReportsIdRouteImport
      parentRoute: typeof MyRouteRoute
    }
    '/api/public/ad-credit/gateway-webhook': {
      id: '/api/public/ad-credit/gateway-webhook'
      path: '/api/public/ad-credit/gateway-webhook'
      fullPath: '/api/public/ad-credit/gateway-webhook'
      preLoaderRoute: typeof ApiPublicAdCreditGatewayWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/otp/linksyria-status': {
      id: '/api/public/otp/linksyria-status'
      path: '/api/public/otp/linksyria-status'
      fullPath: '/api/public/otp/linksyria-status'
      preLoaderRoute: typeof ApiPublicOtpLinksyriaStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my/ads/$id/edit': {
      id: '/my/ads/$id/edit'
      path: '/ads/$id/edit'
      fullPath: '/my/ads/$id/edit'
      preLoaderRoute: typeof MyAdsIdEditRouteImport
      parentRoute: typeof MyRouteRoute
    }
    '/services/$slug/$itemId/book': {
      id: '/services/$slug/$itemId/book'
      path: '/$slug/$itemId/book'
      fullPath: '/services/$slug/$itemId/book'
      preLoaderRoute: typeof ServicesSlugItemIdBookRouteImport
      parentRoute: typeof ServicesRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminAdCreditRoute: typeof AdminAdCreditRoute
  AdminApplicationsRoute: typeof AdminApplicationsRoute
  AdminAuditLogRoute: typeof AdminAuditLogRoute
  AdminBusinessesRoute: typeof AdminBusinessesRoute
  AdminCampaignsRoute: typeof AdminCampaignsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminErrandsRoute: typeof AdminErrandsRoute
  AdminGuideQueueRoute: typeof AdminGuideQueueRoute
  AdminListingEventsRoute: typeof AdminListingEventsRoute
  AdminListingReportsRoute: typeof AdminListingReportsRoute
  AdminListingsRoute: typeof AdminListingsRoute
  AdminLocationsRoute: typeof AdminLocationsRoute
  AdminMascotsRoute: typeof AdminMascotsRoute
  AdminModerationRoute: typeof AdminModerationRoute
  AdminMyWorkRoute: typeof AdminMyWorkRoute
  AdminRolesRoute: typeof AdminRolesRoute
  AdminSearchRoute: typeof AdminSearchRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminStoresRoute: typeof AdminStoresRoute
  AdminStudentBotRoute: typeof AdminStudentBotRoute
  AdminTaxonomyRoute: typeof AdminTaxonomyRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminVerificationsRoute: typeof AdminVerificationsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminBusinessesIdRoute: typeof AdminBusinessesIdRoute
  AdminListingsIdRoute: typeof AdminListingsIdRoute
  AdminReportsIdRoute: typeof AdminReportsIdRoute
  AdminStaffAttendanceRoute: typeof AdminStaffAttendanceRoute
  AdminStaffWorkloadRoute: typeof AdminStaffWorkloadRoute
  AdminUsersIdRoute: typeof AdminUsersIdRoute
  AdminVerificationsIdRoute: typeof AdminVerificationsIdRoute
  AdminReportsIndexRoute: typeof AdminReportsIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAdCreditRoute: AdminAdCreditRoute,
  AdminApplicationsRoute: AdminApplicationsRoute,
  AdminAuditLogRoute: AdminAuditLogRoute,
  AdminBusinessesRoute: AdminBusinessesRoute,
  AdminCampaignsRoute: AdminCampaignsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminErrandsRoute: AdminErrandsRoute,
  AdminGuideQueueRoute: AdminGuideQueueRoute,
  AdminListingEventsRoute: AdminListingEventsRoute,
  AdminListingReportsRoute: AdminListingReportsRoute,
  AdminListingsRoute: AdminListingsRoute,
  AdminLocationsRoute: AdminLocationsRoute,
  AdminMascotsRoute: AdminMascotsRoute,
  AdminModerationRoute: AdminModerationRoute,
  AdminMyWorkRoute: AdminMyWorkRoute,
  AdminRolesRoute: AdminRolesRoute,
  AdminSearchRoute: AdminSearchRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminStoresRoute: AdminStoresRoute,
  AdminStudentBotRoute: AdminStudentBotRoute,
  AdminTaxonomyRoute: AdminTaxonomyRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminVerificationsRoute: AdminVerificationsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminBusinessesIdRoute: AdminBusinessesIdRoute,
  AdminListingsIdRoute: AdminListingsIdRoute,
  AdminReportsIdRoute: AdminReportsIdRoute,
  AdminStaffAttendanceRoute: AdminStaffAttendanceRoute,
  AdminStaffWorkloadRoute: AdminStaffWorkloadRoute,
  AdminUsersIdRoute: AdminUsersIdRoute,
  AdminVerificationsIdRoute: AdminVerificationsIdRoute,
  AdminReportsIndexRoute: AdminReportsIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface BusinessRouteRouteChildren {
  BusinessOrdersRoute: typeof BusinessOrdersRoute
  BusinessPartnersRoute: typeof BusinessPartnersRoute
  BusinessProfileRoute: typeof BusinessProfileRoute
  BusinessIndexRoute: typeof BusinessIndexRoute
  BusinessServicesSettingsRoute: typeof BusinessServicesSettingsRoute
  BusinessStoreCatalogRoute: typeof BusinessStoreCatalogRoute
  BusinessStoreNewRoute: typeof BusinessStoreNewRoute
  BusinessStoreOffersRoute: typeof BusinessStoreOffersRoute
  BusinessServicesIndexRoute: typeof BusinessServicesIndexRoute
  BusinessStoreIndexRoute: typeof BusinessStoreIndexRoute
}

const BusinessRouteRouteChildren: BusinessRouteRouteChildren = {
  BusinessOrdersRoute: BusinessOrdersRoute,
  BusinessPartnersRoute: BusinessPartnersRoute,
  BusinessProfileRoute: BusinessProfileRoute,
  BusinessIndexRoute: BusinessIndexRoute,
  BusinessServicesSettingsRoute: BusinessServicesSettingsRoute,
  BusinessStoreCatalogRoute: BusinessStoreCatalogRoute,
  BusinessStoreNewRoute: BusinessStoreNewRoute,
  BusinessStoreOffersRoute: BusinessStoreOffersRoute,
  BusinessServicesIndexRoute: BusinessServicesIndexRoute,
  BusinessStoreIndexRoute: BusinessStoreIndexRoute,
}

const BusinessRouteRouteWithChildren = BusinessRouteRoute._addFileChildren(
  BusinessRouteRouteChildren,
)

interface MyRouteRouteChildren {
  MyAdCreditRoute: typeof MyAdCreditRoute
  MyBookingsRoute: typeof MyBookingsRoute
  MyCaptainRoute: typeof MyCaptainRoute
  MyFavoritesRoute: typeof MyFavoritesRoute
  MyMessagesRoute: typeof MyMessagesRoute
  MyNotificationsRoute: typeof MyNotificationsRoute
  MyOrdersRoute: typeof MyOrdersRoute
  MyProfileRoute: typeof MyProfileRoute
  MyQuotesRoute: typeof MyQuotesRoute
  MyViolationsRoute: typeof MyViolationsRoute
  MyWalletRoute: typeof MyWalletRoute
  MyAdsNewRoute: typeof MyAdsNewRoute
  MyErrandsIdRoute: typeof MyErrandsIdRoute
  MyReportsIdRoute: typeof MyReportsIdRoute
  MyAdsIndexRoute: typeof MyAdsIndexRoute
  MyErrandsIndexRoute: typeof MyErrandsIndexRoute
  MyReportsIndexRoute: typeof MyReportsIndexRoute
  MyAdsIdEditRoute: typeof MyAdsIdEditRoute
}

const MyRouteRouteChildren: MyRouteRouteChildren = {
  MyAdCreditRoute: MyAdCreditRoute,
  MyBookingsRoute: MyBookingsRoute,
  MyCaptainRoute: MyCaptainRoute,
  MyFavoritesRoute: MyFavoritesRoute,
  MyMessagesRoute: MyMessagesRoute,
  MyNotificationsRoute: MyNotificationsRoute,
  MyOrdersRoute: MyOrdersRoute,
  MyProfileRoute: MyProfileRoute,
  MyQuotesRoute: MyQuotesRoute,
  MyViolationsRoute: MyViolationsRoute,
  MyWalletRoute: MyWalletRoute,
  MyAdsNewRoute: MyAdsNewRoute,
  MyErrandsIdRoute: MyErrandsIdRoute,
  MyReportsIdRoute: MyReportsIdRoute,
  MyAdsIndexRoute: MyAdsIndexRoute,
  MyErrandsIndexRoute: MyErrandsIndexRoute,
  MyReportsIndexRoute: MyReportsIndexRoute,
  MyAdsIdEditRoute: MyAdsIdEditRoute,
}

const MyRouteRouteWithChildren =
  MyRouteRoute._addFileChildren(MyRouteRouteChildren)

interface ServicesRouteChildren {
  ServicesIndexRoute: typeof ServicesIndexRoute
  ServicesSlugItemIdBookRoute: typeof ServicesSlugItemIdBookRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesIndexRoute: ServicesIndexRoute,
  ServicesSlugItemIdBookRoute: ServicesSlugItemIdBookRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  BusinessRouteRoute: BusinessRouteRouteWithChildren,
  MyRouteRoute: MyRouteRouteWithChildren,
  SplatRoute: SplatRoute,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  ChooseAccountRoute: ChooseAccountRoute,
  DemoRoute: DemoRoute,
  ErrandsRoute: ErrandsRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  GoRoute: GoRoute,
  HelpRoute: HelpRoute,
  JoinRoute: JoinRoute,
  KidsRoute: KidsRoute,
  MarketSetupRoute: MarketSetupRoute,
  MoreRoute: MoreRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SearchRoute: SearchRoute,
  ServicesRoute: ServicesRouteWithChildren,
  AdsSlugRoute: AdsSlugRoute,
  BusinessesSlugRoute: BusinessesSlugRoute,
  CategoriesSlugRoute: CategoriesSlugRoute,
  DemoStoresWorldIdRoute: DemoStoresWorldIdRoute,
  GuidesStudentsRoute: GuidesStudentsRoute,
  GuidesSyriaRoute: GuidesSyriaRoute,
  InviteTokenRoute: InviteTokenRoute,
  LegalCopyrightRoute: LegalCopyrightRoute,
  LegalTermsRoute: LegalTermsRoute,
  ProfilesUsernameRoute: ProfilesUsernameRoute,
  StoresSlugRoute: StoresSlugRoute,
  ApiPublicKaheelIntroDotpdfRoute: ApiPublicKaheelIntroDotpdfRoute,
  GuidesStudentsAssistantRoute: GuidesStudentsAssistantRoute,
  GuidesSyriaSlugRoute: GuidesSyriaSlugRoute,
  ApiPublicAdCreditGatewayWebhookRoute: ApiPublicAdCreditGatewayWebhookRoute,
  ApiPublicOtpLinksyriaStatusRoute: ApiPublicOtpLinksyriaStatusRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
