/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ChooseAccountRouteImport } from './routes/choose-account'
import { Route as MarketSetupRouteImport } from './routes/market-setup'
import { Route as MeRouteImport } from './routes/me'
import { Route as MoreRouteImport } from './routes/more'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as SearchRouteImport } from './routes/search'
import { Route as VerifyInvoiceRouteImport } from './routes/verify-invoice'
import { Route as AuthenticatedAuditRouteImport } from './routes/_authenticated/audit'
import { Route as AuthenticatedCustodyRouteImport } from './routes/_authenticated/custody'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedInvitationsRouteImport } from './routes/_authenticated/invitations'
import { Route as AuthenticatedInvoicesRouteImport } from './routes/_authenticated/invoices'
import { Route as AuthenticatedMyCustodyRouteImport } from './routes/_authenticated/my-custody'
import { Route as AuthenticatedMyDocumentsRouteImport } from './routes/_authenticated/my-documents'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedPortalRouteImport } from './routes/_authenticated/portal'
import { Route as AuthenticatedProductsRouteImport } from './routes/_authenticated/products'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedSelectAccountRouteImport } from './routes/_authenticated/select-account'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSuppliersRouteImport } from './routes/_authenticated/suppliers'
import { Route as AuthenticatedTeamRouteImport } from './routes/_authenticated/team'
import { Route as AuthenticatedTrashRouteImport } from './routes/_authenticated/trash'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminActivitiesRouteImport } from './routes/admin/activities'
import { Route as AdminAuditLogRouteImport } from './routes/admin/audit-log'
import { Route as AdminBusinessesRouteImport } from './routes/admin/businesses'
import { Route as AdminGeoRouteImport } from './routes/admin/geo'
import { Route as AdminListingEventsRouteImport } from './routes/admin/listing-events'
import { Route as AdminListingReportsRouteImport } from './routes/admin/listing-reports'
import { Route as AdminListingsRouteImport } from './routes/admin/listings'
import { Route as AdminRolesRouteImport } from './routes/admin/roles'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminVerificationsRouteImport } from './routes/admin/verifications'
import { Route as AdsSlugRouteImport } from './routes/ads.$slug'
import { Route as BusinessNewRouteImport } from './routes/business.new'
import { Route as BusinessesSlugRouteImport } from './routes/businesses.$slug'
import { Route as CategoriesSlugRouteImport } from './routes/categories.$slug'
import { Route as DashboardBusinessRouteImport } from './routes/dashboard/business'
import { Route as DashboardFavoritesRouteImport } from './routes/dashboard/favorites'
import { Route as DashboardMessagesRouteImport } from './routes/dashboard/messages'
import { Route as DashboardMyAdsRouteImport } from './routes/dashboard/my-ads'
import { Route as DashboardNotificationsRouteImport } from './routes/dashboard/notifications'
import { Route as DashboardProfileRouteImport } from './routes/dashboard/profile'
import { Route as DashboardRequestsRouteImport } from './routes/dashboard/requests'
import { Route as DashboardViolationsRouteImport } from './routes/dashboard/violations'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as UUsernameRouteImport } from './routes/u.$username'
import { Route as AuthenticatedProjectsIndexRouteImport } from './routes/_authenticated/projects.index'
import { Route as AuthenticatedProjectsIdRouteImport } from './routes/_authenticated/projects.$id'
import { Route as AuthenticatedRequestsIndexRouteImport } from './routes/_authenticated/requests.index'
import { Route as AuthenticatedRequestsIdRouteImport } from './routes/_authenticated/requests.$id'
import { Route as AuthenticatedSupervisorsIndexRouteImport } from './routes/_authenticated/supervisors.index'
import { Route as AuthenticatedSupervisorsIdRouteImport } from './routes/_authenticated/supervisors.$id'
import { Route as AdminBusinessesIdRouteImport } from './routes/admin/businesses.$id'
import { Route as AdminListingsIdRouteImport } from './routes/admin/listings.$id'
import { Route as AdminReportsIndexRouteImport } from './routes/admin/reports.index'
import { Route as AdminReportsIdRouteImport } from './routes/admin/reports.$id'
import { Route as AdminUsersIdRouteImport } from './routes/admin/users.$id'
import { Route as AdminVerificationsIdRouteImport } from './routes/admin/verifications.$id'
import { Route as DashboardAdsNewRouteImport } from './routes/dashboard/ads.new'
import { Route as DashboardReportsIndexRouteImport } from './routes/dashboard/reports.index'
import { Route as DashboardReportsIdRouteImport } from './routes/dashboard/reports.$id'
import { Route as AuthenticatedInvoicesIdLinesRouteImport } from './routes/_authenticated/invoices_.$id.lines'
import { Route as AuthenticatedInvoicesVerifiedNewRouteImport } from './routes/_authenticated/invoices_.verified.new'
import { Route as AuthenticatedProjectsIdRequestsRouteImport } from './routes/_authenticated/projects_.$id.requests'
import { Route as DashboardAdsIdEditRouteImport } from './routes/dashboard/ads.$id.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ChooseAccountRoute = ChooseAccountRouteImport.update({
  id: '/choose-account',
  path: '/choose-account',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketSetupRoute = MarketSetupRouteImport.update({
  id: '/market-setup',
  path: '/market-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const MeRoute = MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const MoreRoute = MoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyInvoiceRoute = VerifyInvoiceRouteImport.update({
  id: '/verify-invoice',
  path: '/verify-invoice',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAuditRoute = AuthenticatedAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCustodyRoute = AuthenticatedCustodyRouteImport.update({
  id: '/custody',
  path: '/custody',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInvitationsRoute =
  AuthenticatedInvitationsRouteImport.update({
    id: '/invitations',
    path: '/invitations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInvoicesRoute = AuthenticatedInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMyCustodyRoute = AuthenticatedMyCustodyRouteImport.update({
  id: '/my-custody',
  path: '/my-custody',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMyDocumentsRoute =
  AuthenticatedMyDocumentsRouteImport.update({
    id: '/my-documents',
    path: '/my-documents',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPortalRoute = AuthenticatedPortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProductsRoute = AuthenticatedProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSelectAccountRoute =
  AuthenticatedSelectAccountRouteImport.update({
    id: '/select-account',
    path: '/select-account',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSuppliersRoute = AuthenticatedSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTeamRoute = AuthenticatedTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTrashRoute = AuthenticatedTrashRouteImport.update({
  id: '/trash',
  path: '/trash',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminActivitiesRoute = AdminActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAuditLogRoute = AdminAuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminBusinessesRoute = AdminBusinessesRouteImport.update({
  id: '/businesses',
  path: '/businesses',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminGeoRoute = AdminGeoRouteImport.update({
  id: '/geo',
  path: '/geo',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminListingEventsRoute = AdminListingEventsRouteImport.update({
  id: '/listing-events',
  path: '/listing-events',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminListingReportsRoute = AdminListingReportsRouteImport.update({
  id: '/listing-reports',
  path: '/listing-reports',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminListingsRoute = AdminListingsRouteImport.update({
  id: '/listings',
  path: '/listings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminRolesRoute = AdminRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminVerificationsRoute = AdminVerificationsRouteImport.update({
  id: '/verifications',
  path: '/verifications',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdsSlugRoute = AdsSlugRouteImport.update({
  id: '/ads/$slug',
  path: '/ads/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessNewRoute = BusinessNewRouteImport.update({
  id: '/business/new',
  path: '/business/new',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessesSlugRoute = BusinessesSlugRouteImport.update({
  id: '/businesses/$slug',
  path: '/businesses/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesSlugRoute = CategoriesSlugRouteImport.update({
  id: '/categories/$slug',
  path: '/categories/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardBusinessRoute = DashboardBusinessRouteImport.update({
  id: '/dashboard/business',
  path: '/dashboard/business',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardFavoritesRoute = DashboardFavoritesRouteImport.update({
  id: '/dashboard/favorites',
  path: '/dashboard/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardMessagesRoute = DashboardMessagesRouteImport.update({
  id: '/dashboard/messages',
  path: '/dashboard/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardMyAdsRoute = DashboardMyAdsRouteImport.update({
  id: '/dashboard/my-ads',
  path: '/dashboard/my-ads',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardNotificationsRoute = DashboardNotificationsRouteImport.update({
  id: '/dashboard/notifications',
  path: '/dashboard/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/dashboard/profile',
  path: '/dashboard/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRequestsRoute = DashboardRequestsRouteImport.update({
  id: '/dashboard/requests',
  path: '/dashboard/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardViolationsRoute = DashboardViolationsRouteImport.update({
  id: '/dashboard/violations',
  path: '/dashboard/violations',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const UUsernameRoute = UUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProjectsIndexRoute =
  AuthenticatedProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsIdRoute = AuthenticatedProjectsIdRouteImport.update({
  id: '/projects/$id',
  path: '/projects/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRequestsIndexRoute =
  AuthenticatedRequestsIndexRouteImport.update({
    id: '/requests/',
    path: '/requests/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRequestsIdRoute = AuthenticatedRequestsIdRouteImport.update({
  id: '/requests/$id',
  path: '/requests/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSupervisorsIndexRoute =
  AuthenticatedSupervisorsIndexRouteImport.update({
    id: '/supervisors/',
    path: '/supervisors/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSupervisorsIdRoute =
  AuthenticatedSupervisorsIdRouteImport.update({
    id: '/supervisors/$id',
    path: '/supervisors/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AdminBusinessesIdRoute = AdminBusinessesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminBusinessesRoute,
} as any)
const AdminListingsIdRoute = AdminListingsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminListingsRoute,
} as any)
const AdminReportsIndexRoute = AdminReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminReportsIdRoute = AdminReportsIdRouteImport.update({
  id: '/reports/$id',
  path: '/reports/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUsersIdRoute = AdminUsersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminUsersRoute,
} as any)
const AdminVerificationsIdRoute = AdminVerificationsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminVerificationsRoute,
} as any)
const DashboardAdsNewRoute = DashboardAdsNewRouteImport.update({
  id: '/dashboard/ads/new',
  path: '/dashboard/ads/new',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardReportsIndexRoute = DashboardReportsIndexRouteImport.update({
  id: '/dashboard/reports/',
  path: '/dashboard/reports/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardReportsIdRoute = DashboardReportsIdRouteImport.update({
  id: '/dashboard/reports/$id',
  path: '/dashboard/reports/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedInvoicesIdLinesRoute =
  AuthenticatedInvoicesIdLinesRouteImport.update({
    id: '/invoices_/$id/lines',
    path: '/invoices/$id/lines',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInvoicesVerifiedNewRoute =
  AuthenticatedInvoicesVerifiedNewRouteImport.update({
    id: '/invoices_/verified/new',
    path: '/invoices/verified/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsIdRequestsRoute =
  AuthenticatedProjectsIdRequestsRouteImport.update({
    id: '/projects_/$id/requests',
    path: '/projects/$id/requests',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const DashboardAdsIdEditRoute = DashboardAdsIdEditRouteImport.update({
  id: '/dashboard/ads/$id/edit',
  path: '/dashboard/ads/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/$': typeof SplatRoute
  '/auth': typeof AuthRoute
  '/choose-account': typeof ChooseAccountRoute
  '/market-setup': typeof MarketSetupRoute
  '/me': typeof MeRoute
  '/more': typeof MoreRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/verify-invoice': typeof VerifyInvoiceRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/custody': typeof AuthenticatedCustodyRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/invitations': typeof AuthenticatedInvitationsRoute
  '/invoices': typeof AuthenticatedInvoicesRoute
  '/my-custody': typeof AuthenticatedMyCustodyRoute
  '/my-documents': typeof AuthenticatedMyDocumentsRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/portal': typeof AuthenticatedPortalRoute
  '/products': typeof AuthenticatedProductsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/select-account': typeof AuthenticatedSelectAccountRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/suppliers': typeof AuthenticatedSuppliersRoute
  '/team': typeof AuthenticatedTeamRoute
  '/trash': typeof AuthenticatedTrashRoute
  '/users': typeof AuthenticatedUsersRoute
  '/admin/activities': typeof AdminActivitiesRoute
  '/admin/audit-log': typeof AdminAuditLogRoute
  '/admin/businesses': typeof AdminBusinessesRouteWithChildren
  '/admin/geo': typeof AdminGeoRoute
  '/admin/listing-events': typeof AdminListingEventsRoute
  '/admin/listing-reports': typeof AdminListingReportsRoute
  '/admin/listings': typeof AdminListingsRouteWithChildren
  '/admin/roles': typeof AdminRolesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/admin/verifications': typeof AdminVerificationsRouteWithChildren
  '/ads/$slug': typeof AdsSlugRoute
  '/business/new': typeof BusinessNewRoute
  '/businesses/$slug': typeof BusinessesSlugRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/dashboard/business': typeof DashboardBusinessRoute
  '/dashboard/favorites': typeof DashboardFavoritesRoute
  '/dashboard/messages': typeof DashboardMessagesRoute
  '/dashboard/my-ads': typeof DashboardMyAdsRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/requests': typeof DashboardRequestsRoute
  '/dashboard/violations': typeof DashboardViolationsRoute
  '/invite/$token': typeof InviteTokenRoute
  '/u/$username': typeof UUsernameRoute
  '/admin/': typeof AdminIndexRoute
  '/projects/$id': typeof AuthenticatedProjectsIdRoute
  '/requests/$id': typeof AuthenticatedRequestsIdRoute
  '/supervisors/$id': typeof AuthenticatedSupervisorsIdRoute
  '/admin/businesses/$id': typeof AdminBusinessesIdRoute
  '/admin/listings/$id': typeof AdminListingsIdRoute
  '/admin/reports/$id': typeof AdminReportsIdRoute
  '/admin/users/$id': typeof AdminUsersIdRoute
  '/admin/verifications/$id': typeof AdminVerificationsIdRoute
  '/dashboard/ads/new': typeof DashboardAdsNewRoute
  '/dashboard/reports/$id': typeof DashboardReportsIdRoute
  '/projects/': typeof AuthenticatedProjectsIndexRoute
  '/requests/': typeof AuthenticatedRequestsIndexRoute
  '/supervisors/': typeof AuthenticatedSupervisorsIndexRoute
  '/admin/reports/': typeof AdminReportsIndexRoute
  '/dashboard/reports/': typeof DashboardReportsIndexRoute
  '/invoices/$id/lines': typeof AuthenticatedInvoicesIdLinesRoute
  '/invoices/verified/new': typeof AuthenticatedInvoicesVerifiedNewRoute
  '/projects/$id/requests': typeof AuthenticatedProjectsIdRequestsRoute
  '/dashboard/ads/$id/edit': typeof DashboardAdsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/auth': typeof AuthRoute
  '/choose-account': typeof ChooseAccountRoute
  '/market-setup': typeof MarketSetupRoute
  '/me': typeof MeRoute
  '/more': typeof MoreRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/verify-invoice': typeof VerifyInvoiceRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/custody': typeof AuthenticatedCustodyRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/invitations': typeof AuthenticatedInvitationsRoute
  '/invoices': typeof AuthenticatedInvoicesRoute
  '/my-custody': typeof AuthenticatedMyCustodyRoute
  '/my-documents': typeof AuthenticatedMyDocumentsRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/portal': typeof AuthenticatedPortalRoute
  '/products': typeof AuthenticatedProductsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/select-account': typeof AuthenticatedSelectAccountRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/suppliers': typeof AuthenticatedSuppliersRoute
  '/team': typeof AuthenticatedTeamRoute
  '/trash': typeof AuthenticatedTrashRoute
  '/users': typeof AuthenticatedUsersRoute
  '/admin/activities': typeof AdminActivitiesRoute
  '/admin/audit-log': typeof AdminAuditLogRoute
  '/admin/businesses': typeof AdminBusinessesRouteWithChildren
  '/admin/geo': typeof AdminGeoRoute
  '/admin/listing-events': typeof AdminListingEventsRoute
  '/admin/listing-reports': typeof AdminListingReportsRoute
  '/admin/listings': typeof AdminListingsRouteWithChildren
  '/admin/roles': typeof AdminRolesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/admin/verifications': typeof AdminVerificationsRouteWithChildren
  '/ads/$slug': typeof AdsSlugRoute
  '/business/new': typeof BusinessNewRoute
  '/businesses/$slug': typeof BusinessesSlugRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/dashboard/business': typeof DashboardBusinessRoute
  '/dashboard/favorites': typeof DashboardFavoritesRoute
  '/dashboard/messages': typeof DashboardMessagesRoute
  '/dashboard/my-ads': typeof DashboardMyAdsRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/requests': typeof DashboardRequestsRoute
  '/dashboard/violations': typeof DashboardViolationsRoute
  '/invite/$token': typeof InviteTokenRoute
  '/u/$username': typeof UUsernameRoute
  '/admin': typeof AdminIndexRoute
  '/projects/$id': typeof AuthenticatedProjectsIdRoute
  '/requests/$id': typeof AuthenticatedRequestsIdRoute
  '/supervisors/$id': typeof AuthenticatedSupervisorsIdRoute
  '/admin/businesses/$id': typeof AdminBusinessesIdRoute
  '/admin/listings/$id': typeof AdminListingsIdRoute
  '/admin/reports/$id': typeof AdminReportsIdRoute
  '/admin/users/$id': typeof AdminUsersIdRoute
  '/admin/verifications/$id': typeof AdminVerificationsIdRoute
  '/dashboard/ads/new': typeof DashboardAdsNewRoute
  '/dashboard/reports/$id': typeof DashboardReportsIdRoute
  '/projects': typeof AuthenticatedProjectsIndexRoute
  '/requests': typeof AuthenticatedRequestsIndexRoute
  '/supervisors': typeof AuthenticatedSupervisorsIndexRoute
  '/admin/reports': typeof AdminReportsIndexRoute
  '/dashboard/reports': typeof DashboardReportsIndexRoute
  '/invoices/$id/lines': typeof AuthenticatedInvoicesIdLinesRoute
  '/invoices/verified/new': typeof AuthenticatedInvoicesVerifiedNewRoute
  '/projects/$id/requests': typeof AuthenticatedProjectsIdRequestsRoute
  '/dashboard/ads/$id/edit': typeof DashboardAdsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/$': typeof SplatRoute
  '/auth': typeof AuthRoute
  '/choose-account': typeof ChooseAccountRoute
  '/market-setup': typeof MarketSetupRoute
  '/me': typeof MeRoute
  '/more': typeof MoreRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/verify-invoice': typeof VerifyInvoiceRoute
  '/_authenticated/audit': typeof AuthenticatedAuditRoute
  '/_authenticated/custody': typeof AuthenticatedCustodyRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/invitations': typeof AuthenticatedInvitationsRoute
  '/_authenticated/invoices': typeof AuthenticatedInvoicesRoute
  '/_authenticated/my-custody': typeof AuthenticatedMyCustodyRoute
  '/_authenticated/my-documents': typeof AuthenticatedMyDocumentsRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/portal': typeof AuthenticatedPortalRoute
  '/_authenticated/products': typeof AuthenticatedProductsRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/select-account': typeof AuthenticatedSelectAccountRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/suppliers': typeof AuthenticatedSuppliersRoute
  '/_authenticated/team': typeof AuthenticatedTeamRoute
  '/_authenticated/trash': typeof AuthenticatedTrashRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/admin/activities': typeof AdminActivitiesRoute
  '/admin/audit-log': typeof AdminAuditLogRoute
  '/admin/businesses': typeof AdminBusinessesRouteWithChildren
  '/admin/geo': typeof AdminGeoRoute
  '/admin/listing-events': typeof AdminListingEventsRoute
  '/admin/listing-reports': typeof AdminListingReportsRoute
  '/admin/listings': typeof AdminListingsRouteWithChildren
  '/admin/roles': typeof AdminRolesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/admin/verifications': typeof AdminVerificationsRouteWithChildren
  '/ads/$slug': typeof AdsSlugRoute
  '/business/new': typeof BusinessNewRoute
  '/businesses/$slug': typeof BusinessesSlugRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/dashboard/business': typeof DashboardBusinessRoute
  '/dashboard/favorites': typeof DashboardFavoritesRoute
  '/dashboard/messages': typeof DashboardMessagesRoute
  '/dashboard/my-ads': typeof DashboardMyAdsRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/requests': typeof DashboardRequestsRoute
  '/dashboard/violations': typeof DashboardViolationsRoute
  '/invite/$token': typeof InviteTokenRoute
  '/u/$username': typeof UUsernameRoute
  '/admin/': typeof AdminIndexRoute
  '/_authenticated/projects/$id': typeof AuthenticatedProjectsIdRoute
  '/_authenticated/requests/$id': typeof AuthenticatedRequestsIdRoute
  '/_authenticated/supervisors/$id': typeof AuthenticatedSupervisorsIdRoute
  '/admin/businesses/$id': typeof AdminBusinessesIdRoute
  '/admin/listings/$id': typeof AdminListingsIdRoute
  '/admin/reports/$id': typeof AdminReportsIdRoute
  '/admin/users/$id': typeof AdminUsersIdRoute
  '/admin/verifications/$id': typeof AdminVerificationsIdRoute
  '/dashboard/ads/new': typeof DashboardAdsNewRoute
  '/dashboard/reports/$id': typeof DashboardReportsIdRoute
  '/_authenticated/projects/': typeof AuthenticatedProjectsIndexRoute
  '/_authenticated/requests/': typeof AuthenticatedRequestsIndexRoute
  '/_authenticated/supervisors/': typeof AuthenticatedSupervisorsIndexRoute
  '/admin/reports/': typeof AdminReportsIndexRoute
  '/dashboard/reports/': typeof DashboardReportsIndexRoute
  '/_authenticated/invoices_/$id/lines': typeof AuthenticatedInvoicesIdLinesRoute
  '/_authenticated/invoices_/verified/new': typeof AuthenticatedInvoicesVerifiedNewRoute
  '/_authenticated/projects_/$id/requests': typeof AuthenticatedProjectsIdRequestsRoute
  '/dashboard/ads/$id/edit': typeof DashboardAdsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/$'
    | '/auth'
    | '/choose-account'
    | '/market-setup'
    | '/me'
    | '/more'
    | '/register'
    | '/search'
    | '/verify-invoice'
    | '/audit'
    | '/custody'
    | '/dashboard'
    | '/invitations'
    | '/invoices'
    | '/my-custody'
    | '/my-documents'
    | '/notifications'
    | '/onboarding'
    | '/portal'
    | '/products'
    | '/reports'
    | '/select-account'
    | '/settings'
    | '/suppliers'
    | '/team'
    | '/trash'
    | '/users'
    | '/admin/activities'
    | '/admin/audit-log'
    | '/admin/businesses'
    | '/admin/geo'
    | '/admin/listing-events'
    | '/admin/listing-reports'
    | '/admin/listings'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/verifications'
    | '/ads/$slug'
    | '/business/new'
    | '/businesses/$slug'
    | '/categories/$slug'
    | '/dashboard/business'
    | '/dashboard/favorites'
    | '/dashboard/messages'
    | '/dashboard/my-ads'
    | '/dashboard/notifications'
    | '/dashboard/profile'
    | '/dashboard/requests'
    | '/dashboard/violations'
    | '/invite/$token'
    | '/u/$username'
    | '/admin/'
    | '/projects/$id'
    | '/requests/$id'
    | '/supervisors/$id'
    | '/admin/businesses/$id'
    | '/admin/listings/$id'
    | '/admin/reports/$id'
    | '/admin/users/$id'
    | '/admin/verifications/$id'
    | '/dashboard/ads/new'
    | '/dashboard/reports/$id'
    | '/projects/'
    | '/requests/'
    | '/supervisors/'
    | '/admin/reports/'
    | '/dashboard/reports/'
    | '/invoices/$id/lines'
    | '/invoices/verified/new'
    | '/projects/$id/requests'
    | '/dashboard/ads/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/auth'
    | '/choose-account'
    | '/market-setup'
    | '/me'
    | '/more'
    | '/register'
    | '/search'
    | '/verify-invoice'
    | '/audit'
    | '/custody'
    | '/dashboard'
    | '/invitations'
    | '/invoices'
    | '/my-custody'
    | '/my-documents'
    | '/notifications'
    | '/onboarding'
    | '/portal'
    | '/products'
    | '/reports'
    | '/select-account'
    | '/settings'
    | '/suppliers'
    | '/team'
    | '/trash'
    | '/users'
    | '/admin/activities'
    | '/admin/audit-log'
    | '/admin/businesses'
    | '/admin/geo'
    | '/admin/listing-events'
    | '/admin/listing-reports'
    | '/admin/listings'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/verifications'
    | '/ads/$slug'
    | '/business/new'
    | '/businesses/$slug'
    | '/categories/$slug'
    | '/dashboard/business'
    | '/dashboard/favorites'
    | '/dashboard/messages'
    | '/dashboard/my-ads'
    | '/dashboard/notifications'
    | '/dashboard/profile'
    | '/dashboard/requests'
    | '/dashboard/violations'
    | '/invite/$token'
    | '/u/$username'
    | '/admin'
    | '/projects/$id'
    | '/requests/$id'
    | '/supervisors/$id'
    | '/admin/businesses/$id'
    | '/admin/listings/$id'
    | '/admin/reports/$id'
    | '/admin/users/$id'
    | '/admin/verifications/$id'
    | '/dashboard/ads/new'
    | '/dashboard/reports/$id'
    | '/projects'
    | '/requests'
    | '/supervisors'
    | '/admin/reports'
    | '/dashboard/reports'
    | '/invoices/$id/lines'
    | '/invoices/verified/new'
    | '/projects/$id/requests'
    | '/dashboard/ads/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin'
    | '/$'
    | '/auth'
    | '/choose-account'
    | '/market-setup'
    | '/me'
    | '/more'
    | '/register'
    | '/search'
    | '/verify-invoice'
    | '/_authenticated/audit'
    | '/_authenticated/custody'
    | '/_authenticated/dashboard'
    | '/_authenticated/invitations'
    | '/_authenticated/invoices'
    | '/_authenticated/my-custody'
    | '/_authenticated/my-documents'
    | '/_authenticated/notifications'
    | '/_authenticated/onboarding'
    | '/_authenticated/portal'
    | '/_authenticated/products'
    | '/_authenticated/reports'
    | '/_authenticated/select-account'
    | '/_authenticated/settings'
    | '/_authenticated/suppliers'
    | '/_authenticated/team'
    | '/_authenticated/trash'
    | '/_authenticated/users'
    | '/admin/activities'
    | '/admin/audit-log'
    | '/admin/businesses'
    | '/admin/geo'
    | '/admin/listing-events'
    | '/admin/listing-reports'
    | '/admin/listings'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/verifications'
    | '/ads/$slug'
    | '/business/new'
    | '/businesses/$slug'
    | '/categories/$slug'
    | '/dashboard/business'
    | '/dashboard/favorites'
    | '/dashboard/messages'
    | '/dashboard/my-ads'
    | '/dashboard/notifications'
    | '/dashboard/profile'
    | '/dashboard/requests'
    | '/dashboard/violations'
    | '/invite/$token'
    | '/u/$username'
    | '/admin/'
    | '/_authenticated/projects/$id'
    | '/_authenticated/requests/$id'
    | '/_authenticated/supervisors/$id'
    | '/admin/businesses/$id'
    | '/admin/listings/$id'
    | '/admin/reports/$id'
    | '/admin/users/$id'
    | '/admin/verifications/$id'
    | '/dashboard/ads/new'
    | '/dashboard/reports/$id'
    | '/_authenticated/projects/'
    | '/_authenticated/requests/'
    | '/_authenticated/supervisors/'
    | '/admin/reports/'
    | '/dashboard/reports/'
    | '/_authenticated/invoices_/$id/lines'
    | '/_authenticated/invoices_/verified/new'
    | '/_authenticated/projects_/$id/requests'
    | '/dashboard/ads/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  SplatRoute: typeof SplatRoute
  AuthRoute: typeof AuthRoute
  ChooseAccountRoute: typeof ChooseAccountRoute
  MarketSetupRoute: typeof MarketSetupRoute
  MeRoute: typeof MeRoute
  MoreRoute: typeof MoreRoute
  RegisterRoute: typeof RegisterRoute
  SearchRoute: typeof SearchRoute
  VerifyInvoiceRoute: typeof VerifyInvoiceRoute
  AdsSlugRoute: typeof AdsSlugRoute
  BusinessNewRoute: typeof BusinessNewRoute
  BusinessesSlugRoute: typeof BusinessesSlugRoute
  CategoriesSlugRoute: typeof CategoriesSlugRoute
  DashboardBusinessRoute: typeof DashboardBusinessRoute
  DashboardFavoritesRoute: typeof DashboardFavoritesRoute
  DashboardMessagesRoute: typeof DashboardMessagesRoute
  DashboardMyAdsRoute: typeof DashboardMyAdsRoute
  DashboardNotificationsRoute: typeof DashboardNotificationsRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardRequestsRoute: typeof DashboardRequestsRoute
  DashboardViolationsRoute: typeof DashboardViolationsRoute
  InviteTokenRoute: typeof InviteTokenRoute
  UUsernameRoute: typeof UUsernameRoute
  DashboardAdsNewRoute: typeof DashboardAdsNewRoute
  DashboardReportsIdRoute: typeof DashboardReportsIdRoute
  DashboardReportsIndexRoute: typeof DashboardReportsIndexRoute
  DashboardAdsIdEditRoute: typeof DashboardAdsIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/choose-account': {
      id: '/choose-account'
      path: '/choose-account'
      fullPath: '/choose-account'
      preLoaderRoute: typeof ChooseAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market-setup': {
      id: '/market-setup'
      path: '/market-setup'
      fullPath: '/market-setup'
      preLoaderRoute: typeof MarketSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/more': {
      id: '/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof MoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-invoice': {
      id: '/verify-invoice'
      path: '/verify-invoice'
      fullPath: '/verify-invoice'
      preLoaderRoute: typeof VerifyInvoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/audit': {
      id: '/_authenticated/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuthenticatedAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/custody': {
      id: '/_authenticated/custody'
      path: '/custody'
      fullPath: '/custody'
      preLoaderRoute: typeof AuthenticatedCustodyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/invitations': {
      id: '/_authenticated/invitations'
      path: '/invitations'
      fullPath: '/invitations'
      preLoaderRoute: typeof AuthenticatedInvitationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/invoices': {
      id: '/_authenticated/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof AuthenticatedInvoicesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-custody': {
      id: '/_authenticated/my-custody'
      path: '/my-custody'
      fullPath: '/my-custody'
      preLoaderRoute: typeof AuthenticatedMyCustodyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-documents': {
      id: '/_authenticated/my-documents'
      path: '/my-documents'
      fullPath: '/my-documents'
      preLoaderRoute: typeof AuthenticatedMyDocumentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal': {
      id: '/_authenticated/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof AuthenticatedPortalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/products': {
      id: '/_authenticated/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AuthenticatedProductsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/select-account': {
      id: '/_authenticated/select-account'
      path: '/select-account'
      fullPath: '/select-account'
      preLoaderRoute: typeof AuthenticatedSelectAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/suppliers': {
      id: '/_authenticated/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof AuthenticatedSuppliersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/team': {
      id: '/_authenticated/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AuthenticatedTeamRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/trash': {
      id: '/_authenticated/trash'
      path: '/trash'
      fullPath: '/trash'
      preLoaderRoute: typeof AuthenticatedTrashRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/activities': {
      id: '/admin/activities'
      path: '/activities'
      fullPath: '/admin/activities'
      preLoaderRoute: typeof AdminActivitiesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/audit-log': {
      id: '/admin/audit-log'
      path: '/audit-log'
      fullPath: '/admin/audit-log'
      preLoaderRoute: typeof AdminAuditLogRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/businesses': {
      id: '/admin/businesses'
      path: '/businesses'
      fullPath: '/admin/businesses'
      preLoaderRoute: typeof AdminBusinessesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/geo': {
      id: '/admin/geo'
      path: '/geo'
      fullPath: '/admin/geo'
      preLoaderRoute: typeof AdminGeoRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/listing-events': {
      id: '/admin/listing-events'
      path: '/listing-events'
      fullPath: '/admin/listing-events'
      preLoaderRoute: typeof AdminListingEventsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/listing-reports': {
      id: '/admin/listing-reports'
      path: '/listing-reports'
      fullPath: '/admin/listing-reports'
      preLoaderRoute: typeof AdminListingReportsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/listings': {
      id: '/admin/listings'
      path: '/listings'
      fullPath: '/admin/listings'
      preLoaderRoute: typeof AdminListingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/roles': {
      id: '/admin/roles'
      path: '/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminRolesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/verifications': {
      id: '/admin/verifications'
      path: '/verifications'
      fullPath: '/admin/verifications'
      preLoaderRoute: typeof AdminVerificationsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/ads/$slug': {
      id: '/ads/$slug'
      path: '/ads/$slug'
      fullPath: '/ads/$slug'
      preLoaderRoute: typeof AdsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/new': {
      id: '/business/new'
      path: '/business/new'
      fullPath: '/business/new'
      preLoaderRoute: typeof BusinessNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/businesses/$slug': {
      id: '/businesses/$slug'
      path: '/businesses/$slug'
      fullPath: '/businesses/$slug'
      preLoaderRoute: typeof BusinessesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/$slug': {
      id: '/categories/$slug'
      path: '/categories/$slug'
      fullPath: '/categories/$slug'
      preLoaderRoute: typeof CategoriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/business': {
      id: '/dashboard/business'
      path: '/dashboard/business'
      fullPath: '/dashboard/business'
      preLoaderRoute: typeof DashboardBusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/favorites': {
      id: '/dashboard/favorites'
      path: '/dashboard/favorites'
      fullPath: '/dashboard/favorites'
      preLoaderRoute: typeof DashboardFavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/messages': {
      id: '/dashboard/messages'
      path: '/dashboard/messages'
      fullPath: '/dashboard/messages'
      preLoaderRoute: typeof DashboardMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/my-ads': {
      id: '/dashboard/my-ads'
      path: '/dashboard/my-ads'
      fullPath: '/dashboard/my-ads'
      preLoaderRoute: typeof DashboardMyAdsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/notifications': {
      id: '/dashboard/notifications'
      path: '/dashboard/notifications'
      fullPath: '/dashboard/notifications'
      preLoaderRoute: typeof DashboardNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/dashboard/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/requests': {
      id: '/dashboard/requests'
      path: '/dashboard/requests'
      fullPath: '/dashboard/requests'
      preLoaderRoute: typeof DashboardRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/violations': {
      id: '/dashboard/violations'
      path: '/dashboard/violations'
      fullPath: '/dashboard/violations'
      preLoaderRoute: typeof DashboardViolationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$username': {
      id: '/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof UUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/projects/': {
      id: '/_authenticated/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AuthenticatedProjectsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/$id': {
      id: '/_authenticated/projects/$id'
      path: '/projects/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof AuthenticatedProjectsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/requests/': {
      id: '/_authenticated/requests/'
      path: '/requests'
      fullPath: '/requests/'
      preLoaderRoute: typeof AuthenticatedRequestsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/requests/$id': {
      id: '/_authenticated/requests/$id'
      path: '/requests/$id'
      fullPath: '/requests/$id'
      preLoaderRoute: typeof AuthenticatedRequestsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/supervisors/': {
      id: '/_authenticated/supervisors/'
      path: '/supervisors'
      fullPath: '/supervisors/'
      preLoaderRoute: typeof AuthenticatedSupervisorsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/supervisors/$id': {
      id: '/_authenticated/supervisors/$id'
      path: '/supervisors/$id'
      fullPath: '/supervisors/$id'
      preLoaderRoute: typeof AuthenticatedSupervisorsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/admin/businesses/$id': {
      id: '/admin/businesses/$id'
      path: '/$id'
      fullPath: '/admin/businesses/$id'
      preLoaderRoute: typeof AdminBusinessesIdRouteImport
      parentRoute: typeof AdminBusinessesRoute
    }
    '/admin/listings/$id': {
      id: '/admin/listings/$id'
      path: '/$id'
      fullPath: '/admin/listings/$id'
      preLoaderRoute: typeof AdminListingsIdRouteImport
      parentRoute: typeof AdminListingsRoute
    }
    '/admin/reports/': {
      id: '/admin/reports/'
      path: '/reports'
      fullPath: '/admin/reports/'
      preLoaderRoute: typeof AdminReportsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/reports/$id': {
      id: '/admin/reports/$id'
      path: '/reports/$id'
      fullPath: '/admin/reports/$id'
      preLoaderRoute: typeof AdminReportsIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/users/$id': {
      id: '/admin/users/$id'
      path: '/$id'
      fullPath: '/admin/users/$id'
      preLoaderRoute: typeof AdminUsersIdRouteImport
      parentRoute: typeof AdminUsersRoute
    }
    '/admin/verifications/$id': {
      id: '/admin/verifications/$id'
      path: '/$id'
      fullPath: '/admin/verifications/$id'
      preLoaderRoute: typeof AdminVerificationsIdRouteImport
      parentRoute: typeof AdminVerificationsRoute
    }
    '/dashboard/ads/new': {
      id: '/dashboard/ads/new'
      path: '/dashboard/ads/new'
      fullPath: '/dashboard/ads/new'
      preLoaderRoute: typeof DashboardAdsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/reports/': {
      id: '/dashboard/reports/'
      path: '/dashboard/reports'
      fullPath: '/dashboard/reports/'
      preLoaderRoute: typeof DashboardReportsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/reports/$id': {
      id: '/dashboard/reports/$id'
      path: '/dashboard/reports/$id'
      fullPath: '/dashboard/reports/$id'
      preLoaderRoute: typeof DashboardReportsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/invoices_/$id/lines': {
      id: '/_authenticated/invoices_/$id/lines'
      path: '/invoices/$id/lines'
      fullPath: '/invoices/$id/lines'
      preLoaderRoute: typeof AuthenticatedInvoicesIdLinesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/invoices_/verified/new': {
      id: '/_authenticated/invoices_/verified/new'
      path: '/invoices/verified/new'
      fullPath: '/invoices/verified/new'
      preLoaderRoute: typeof AuthenticatedInvoicesVerifiedNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects_/$id/requests': {
      id: '/_authenticated/projects_/$id/requests'
      path: '/projects/$id/requests'
      fullPath: '/projects/$id/requests'
      preLoaderRoute: typeof AuthenticatedProjectsIdRequestsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/dashboard/ads/$id/edit': {
      id: '/dashboard/ads/$id/edit'
      path: '/dashboard/ads/$id/edit'
      fullPath: '/dashboard/ads/$id/edit'
      preLoaderRoute: typeof DashboardAdsIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAuditRoute: typeof AuthenticatedAuditRoute
  AuthenticatedCustodyRoute: typeof AuthenticatedCustodyRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedInvitationsRoute: typeof AuthenticatedInvitationsRoute
  AuthenticatedInvoicesRoute: typeof AuthenticatedInvoicesRoute
  AuthenticatedMyCustodyRoute: typeof AuthenticatedMyCustodyRoute
  AuthenticatedMyDocumentsRoute: typeof AuthenticatedMyDocumentsRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedPortalRoute: typeof AuthenticatedPortalRoute
  AuthenticatedProductsRoute: typeof AuthenticatedProductsRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSelectAccountRoute: typeof AuthenticatedSelectAccountRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSuppliersRoute: typeof AuthenticatedSuppliersRoute
  AuthenticatedTeamRoute: typeof AuthenticatedTeamRoute
  AuthenticatedTrashRoute: typeof AuthenticatedTrashRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
  AuthenticatedProjectsIdRoute: typeof AuthenticatedProjectsIdRoute
  AuthenticatedRequestsIdRoute: typeof AuthenticatedRequestsIdRoute
  AuthenticatedSupervisorsIdRoute: typeof AuthenticatedSupervisorsIdRoute
  AuthenticatedProjectsIndexRoute: typeof AuthenticatedProjectsIndexRoute
  AuthenticatedRequestsIndexRoute: typeof AuthenticatedRequestsIndexRoute
  AuthenticatedSupervisorsIndexRoute: typeof AuthenticatedSupervisorsIndexRoute
  AuthenticatedInvoicesIdLinesRoute: typeof AuthenticatedInvoicesIdLinesRoute
  AuthenticatedInvoicesVerifiedNewRoute: typeof AuthenticatedInvoicesVerifiedNewRoute
  AuthenticatedProjectsIdRequestsRoute: typeof AuthenticatedProjectsIdRequestsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAuditRoute: AuthenticatedAuditRoute,
  AuthenticatedCustodyRoute: AuthenticatedCustodyRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedInvitationsRoute: AuthenticatedInvitationsRoute,
  AuthenticatedInvoicesRoute: AuthenticatedInvoicesRoute,
  AuthenticatedMyCustodyRoute: AuthenticatedMyCustodyRoute,
  AuthenticatedMyDocumentsRoute: AuthenticatedMyDocumentsRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedPortalRoute: AuthenticatedPortalRoute,
  AuthenticatedProductsRoute: AuthenticatedProductsRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSelectAccountRoute: AuthenticatedSelectAccountRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSuppliersRoute: AuthenticatedSuppliersRoute,
  AuthenticatedTeamRoute: AuthenticatedTeamRoute,
  AuthenticatedTrashRoute: AuthenticatedTrashRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
  AuthenticatedProjectsIdRoute: AuthenticatedProjectsIdRoute,
  AuthenticatedRequestsIdRoute: AuthenticatedRequestsIdRoute,
  AuthenticatedSupervisorsIdRoute: AuthenticatedSupervisorsIdRoute,
  AuthenticatedProjectsIndexRoute: AuthenticatedProjectsIndexRoute,
  AuthenticatedRequestsIndexRoute: AuthenticatedRequestsIndexRoute,
  AuthenticatedSupervisorsIndexRoute: AuthenticatedSupervisorsIndexRoute,
  AuthenticatedInvoicesIdLinesRoute: AuthenticatedInvoicesIdLinesRoute,
  AuthenticatedInvoicesVerifiedNewRoute: AuthenticatedInvoicesVerifiedNewRoute,
  AuthenticatedProjectsIdRequestsRoute: AuthenticatedProjectsIdRequestsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AdminBusinessesRouteChildren {
  AdminBusinessesIdRoute: typeof AdminBusinessesIdRoute
}

const AdminBusinessesRouteChildren: AdminBusinessesRouteChildren = {
  AdminBusinessesIdRoute: AdminBusinessesIdRoute,
}

const AdminBusinessesRouteWithChildren = AdminBusinessesRoute._addFileChildren(
  AdminBusinessesRouteChildren,
)

interface AdminListingsRouteChildren {
  AdminListingsIdRoute: typeof AdminListingsIdRoute
}

const AdminListingsRouteChildren: AdminListingsRouteChildren = {
  AdminListingsIdRoute: AdminListingsIdRoute,
}

const AdminListingsRouteWithChildren = AdminListingsRoute._addFileChildren(
  AdminListingsRouteChildren,
)

interface AdminUsersRouteChildren {
  AdminUsersIdRoute: typeof AdminUsersIdRoute
}

const AdminUsersRouteChildren: AdminUsersRouteChildren = {
  AdminUsersIdRoute: AdminUsersIdRoute,
}

const AdminUsersRouteWithChildren = AdminUsersRoute._addFileChildren(
  AdminUsersRouteChildren,
)

interface AdminVerificationsRouteChildren {
  AdminVerificationsIdRoute: typeof AdminVerificationsIdRoute
}

const AdminVerificationsRouteChildren: AdminVerificationsRouteChildren = {
  AdminVerificationsIdRoute: AdminVerificationsIdRoute,
}

const AdminVerificationsRouteWithChildren =
  AdminVerificationsRoute._addFileChildren(AdminVerificationsRouteChildren)

interface AdminRouteRouteChildren {
  AdminActivitiesRoute: typeof AdminActivitiesRoute
  AdminAuditLogRoute: typeof AdminAuditLogRoute
  AdminBusinessesRoute: typeof AdminBusinessesRouteWithChildren
  AdminGeoRoute: typeof AdminGeoRoute
  AdminListingEventsRoute: typeof AdminListingEventsRoute
  AdminListingReportsRoute: typeof AdminListingReportsRoute
  AdminListingsRoute: typeof AdminListingsRouteWithChildren
  AdminRolesRoute: typeof AdminRolesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRouteWithChildren
  AdminVerificationsRoute: typeof AdminVerificationsRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
  AdminReportsIdRoute: typeof AdminReportsIdRoute
  AdminReportsIndexRoute: typeof AdminReportsIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminActivitiesRoute: AdminActivitiesRoute,
  AdminAuditLogRoute: AdminAuditLogRoute,
  AdminBusinessesRoute: AdminBusinessesRouteWithChildren,
  AdminGeoRoute: AdminGeoRoute,
  AdminListingEventsRoute: AdminListingEventsRoute,
  AdminListingReportsRoute: AdminListingReportsRoute,
  AdminListingsRoute: AdminListingsRouteWithChildren,
  AdminRolesRoute: AdminRolesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRouteWithChildren,
  AdminVerificationsRoute: AdminVerificationsRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
  AdminReportsIdRoute: AdminReportsIdRoute,
  AdminReportsIndexRoute: AdminReportsIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  SplatRoute: SplatRoute,
  AuthRoute: AuthRoute,
  ChooseAccountRoute: ChooseAccountRoute,
  MarketSetupRoute: MarketSetupRoute,
  MeRoute: MeRoute,
  MoreRoute: MoreRoute,
  RegisterRoute: RegisterRoute,
  SearchRoute: SearchRoute,
  VerifyInvoiceRoute: VerifyInvoiceRoute,
  AdsSlugRoute: AdsSlugRoute,
  BusinessNewRoute: BusinessNewRoute,
  BusinessesSlugRoute: BusinessesSlugRoute,
  CategoriesSlugRoute: CategoriesSlugRoute,
  DashboardBusinessRoute: DashboardBusinessRoute,
  DashboardFavoritesRoute: DashboardFavoritesRoute,
  DashboardMessagesRoute: DashboardMessagesRoute,
  DashboardMyAdsRoute: DashboardMyAdsRoute,
  DashboardNotificationsRoute: DashboardNotificationsRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardRequestsRoute: DashboardRequestsRoute,
  DashboardViolationsRoute: DashboardViolationsRoute,
  InviteTokenRoute: InviteTokenRoute,
  UUsernameRoute: UUsernameRoute,
  DashboardAdsNewRoute: DashboardAdsNewRoute,
  DashboardReportsIdRoute: DashboardReportsIdRoute,
  DashboardReportsIndexRoute: DashboardReportsIndexRoute,
  DashboardAdsIdEditRoute: DashboardAdsIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
