/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ChooseAccountRouteImport } from './routes/choose-account'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as HelpRouteImport } from './routes/help'
import { Route as MarketSetupRouteImport } from './routes/market-setup'
import { Route as MeRouteImport } from './routes/me'
import { Route as MoreRouteImport } from './routes/more'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as SearchRouteImport } from './routes/search'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as VerifyInvoiceRouteImport } from './routes/verify-invoice'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminActivitiesRouteImport } from './routes/admin/activities'
import { Route as AdminAttendanceRouteImport } from './routes/admin/attendance'
import { Route as AdminAuditLogRouteImport } from './routes/admin/audit-log'
import { Route as AdminBusinessesRouteImport } from './routes/admin/businesses'
import { Route as AdminContentRulesRouteImport } from './routes/admin/content-rules'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminGeoRouteImport } from './routes/admin/geo'
import { Route as AdminListingEventsRouteImport } from './routes/admin/listing-events'
import { Route as AdminListingReportsRouteImport } from './routes/admin/listing-reports'
import { Route as AdminListingsRouteImport } from './routes/admin/listings'
import { Route as AdminMyWorkRouteImport } from './routes/admin/my-work'
import { Route as AdminRolesRouteImport } from './routes/admin/roles'
import { Route as AdminSearchRouteImport } from './routes/admin/search'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminStoresRouteImport } from './routes/admin/stores'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminVerificationsRouteImport } from './routes/admin/verifications'
import { Route as AdminWorkforceRouteImport } from './routes/admin/workforce'
import { Route as AdsSlugRouteImport } from './routes/ads.$slug'
import { Route as BusinessNewRouteImport } from './routes/business.new'
import { Route as BusinessesSlugRouteImport } from './routes/businesses.$slug'
import { Route as CategoriesSlugRouteImport } from './routes/categories.$slug'
import { Route as DashboardBusinessRouteImport } from './routes/dashboard/business'
import { Route as DashboardFavoritesRouteImport } from './routes/dashboard/favorites'
import { Route as DashboardMessagesRouteImport } from './routes/dashboard/messages'
import { Route as DashboardMyAdsRouteImport } from './routes/dashboard/my-ads'
import { Route as DashboardNotificationsRouteImport } from './routes/dashboard/notifications'
import { Route as DashboardPointsRouteImport } from './routes/dashboard/points'
import { Route as DashboardProfileRouteImport } from './routes/dashboard/profile'
import { Route as DashboardRequestsRouteImport } from './routes/dashboard/requests'
import { Route as DashboardViolationsRouteImport } from './routes/dashboard/violations'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as StoresSlugRouteImport } from './routes/stores.$slug'
import { Route as UUsernameRouteImport } from './routes/u.$username'
import { Route as AdminBusinessesIdRouteImport } from './routes/admin/businesses_.$id'
import { Route as AdminListingsIdRouteImport } from './routes/admin/listings_.$id'
import { Route as AdminReportsIndexRouteImport } from './routes/admin/reports.index'
import { Route as AdminReportsIdRouteImport } from './routes/admin/reports.$id'
import { Route as AdminUsersIdRouteImport } from './routes/admin/users_.$id'
import { Route as AdminVerificationsIdRouteImport } from './routes/admin/verifications_.$id'
import { Route as DashboardAdsNewRouteImport } from './routes/dashboard/ads.new'
import { Route as DashboardReportsIndexRouteImport } from './routes/dashboard/reports.index'
import { Route as DashboardReportsIdRouteImport } from './routes/dashboard/reports.$id'
import { Route as DashboardStoreIndexRouteImport } from './routes/dashboard/store.index'
import { Route as DashboardStoreCatalogRouteImport } from './routes/dashboard/store.catalog'
import { Route as DashboardStoreNewRouteImport } from './routes/dashboard/store.new'
import { Route as DashboardAdsIdEditRouteImport } from './routes/dashboard/ads.$id.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ChooseAccountRoute = ChooseAccountRouteImport.update({
  id: '/choose-account',
  path: '/choose-account',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketSetupRoute = MarketSetupRouteImport.update({
  id: '/market-setup',
  path: '/market-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const MeRoute = MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const MoreRoute = MoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyInvoiceRoute = VerifyInvoiceRouteImport.update({
  id: '/verify-invoice',
  path: '/verify-invoice',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminActivitiesRoute = AdminActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAttendanceRoute = AdminAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAuditLogRoute = AdminAuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminBusinessesRoute = AdminBusinessesRouteImport.update({
  id: '/businesses',
  path: '/businesses',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminContentRulesRoute = AdminContentRulesRouteImport.update({
  id: '/content-rules',
  path: '/content-rules',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminGeoRoute = AdminGeoRouteImport.update({
  id: '/geo',
  path: '/geo',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminListingEventsRoute = AdminListingEventsRouteImport.update({
  id: '/listing-events',
  path: '/listing-events',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminListingReportsRoute = AdminListingReportsRouteImport.update({
  id: '/listing-reports',
  path: '/listing-reports',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminListingsRoute = AdminListingsRouteImport.update({
  id: '/listings',
  path: '/listings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMyWorkRoute = AdminMyWorkRouteImport.update({
  id: '/my-work',
  path: '/my-work',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminRolesRoute = AdminRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSearchRoute = AdminSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminStoresRoute = AdminStoresRouteImport.update({
  id: '/stores',
  path: '/stores',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminVerificationsRoute = AdminVerificationsRouteImport.update({
  id: '/verifications',
  path: '/verifications',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminWorkforceRoute = AdminWorkforceRouteImport.update({
  id: '/workforce',
  path: '/workforce',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdsSlugRoute = AdsSlugRouteImport.update({
  id: '/ads/$slug',
  path: '/ads/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessNewRoute = BusinessNewRouteImport.update({
  id: '/business/new',
  path: '/business/new',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessesSlugRoute = BusinessesSlugRouteImport.update({
  id: '/businesses/$slug',
  path: '/businesses/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesSlugRoute = CategoriesSlugRouteImport.update({
  id: '/categories/$slug',
  path: '/categories/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardBusinessRoute = DashboardBusinessRouteImport.update({
  id: '/dashboard/business',
  path: '/dashboard/business',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardFavoritesRoute = DashboardFavoritesRouteImport.update({
  id: '/dashboard/favorites',
  path: '/dashboard/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardMessagesRoute = DashboardMessagesRouteImport.update({
  id: '/dashboard/messages',
  path: '/dashboard/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardMyAdsRoute = DashboardMyAdsRouteImport.update({
  id: '/dashboard/my-ads',
  path: '/dashboard/my-ads',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardNotificationsRoute = DashboardNotificationsRouteImport.update({
  id: '/dashboard/notifications',
  path: '/dashboard/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardPointsRoute = DashboardPointsRouteImport.update({
  id: '/dashboard/points',
  path: '/dashboard/points',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/dashboard/profile',
  path: '/dashboard/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRequestsRoute = DashboardRequestsRouteImport.update({
  id: '/dashboard/requests',
  path: '/dashboard/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardViolationsRoute = DashboardViolationsRouteImport.update({
  id: '/dashboard/violations',
  path: '/dashboard/violations',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const StoresSlugRoute = StoresSlugRouteImport.update({
  id: '/stores/$slug',
  path: '/stores/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const UUsernameRoute = UUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBusinessesIdRoute = AdminBusinessesIdRouteImport.update({
  id: '/businesses_/$id',
  path: '/businesses/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminListingsIdRoute = AdminListingsIdRouteImport.update({
  id: '/listings_/$id',
  path: '/listings/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminReportsIndexRoute = AdminReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminReportsIdRoute = AdminReportsIdRouteImport.update({
  id: '/reports/$id',
  path: '/reports/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUsersIdRoute = AdminUsersIdRouteImport.update({
  id: '/users_/$id',
  path: '/users/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminVerificationsIdRoute = AdminVerificationsIdRouteImport.update({
  id: '/verifications_/$id',
  path: '/verifications/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)
const DashboardAdsNewRoute = DashboardAdsNewRouteImport.update({
  id: '/dashboard/ads/new',
  path: '/dashboard/ads/new',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardReportsIndexRoute = DashboardReportsIndexRouteImport.update({
  id: '/dashboard/reports/',
  path: '/dashboard/reports/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardReportsIdRoute = DashboardReportsIdRouteImport.update({
  id: '/dashboard/reports/$id',
  path: '/dashboard/reports/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardStoreIndexRoute = DashboardStoreIndexRouteImport.update({
  id: '/dashboard/store/',
  path: '/dashboard/store/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardStoreCatalogRoute = DashboardStoreCatalogRouteImport.update({
  id: '/dashboard/store/catalog',
  path: '/dashboard/store/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardStoreNewRoute = DashboardStoreNewRouteImport.update({
  id: '/dashboard/store/new',
  path: '/dashboard/store/new',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAdsIdEditRoute = DashboardAdsIdEditRouteImport.update({
  id: '/dashboard/ads/$id/edit',
  path: '/dashboard/ads/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/audit': typeof AuditRoute
  '/auth': typeof AuthRoute
  '/choose-account': typeof ChooseAccountRoute
  '/contact': typeof ContactRoute
  '/help': typeof HelpRoute
  '/market-setup': typeof MarketSetupRoute
  '/me': typeof MeRoute
  '/more': typeof MoreRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/terms': typeof TermsRoute
  '/verify-invoice': typeof VerifyInvoiceRoute
  '/welcome': typeof WelcomeRoute
  '/admin/activities': typeof AdminActivitiesRoute
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/audit-log': typeof AdminAuditLogRoute
  '/admin/businesses': typeof AdminBusinessesRoute
  '/admin/content-rules': typeof AdminContentRulesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/geo': typeof AdminGeoRoute
  '/admin/listing-events': typeof AdminListingEventsRoute
  '/admin/listing-reports': typeof AdminListingReportsRoute
  '/admin/listings': typeof AdminListingsRoute
  '/admin/my-work': typeof AdminMyWorkRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/search': typeof AdminSearchRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/stores': typeof AdminStoresRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/verifications': typeof AdminVerificationsRoute
  '/admin/workforce': typeof AdminWorkforceRoute
  '/ads/$slug': typeof AdsSlugRoute
  '/business/new': typeof BusinessNewRoute
  '/businesses/$slug': typeof BusinessesSlugRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/dashboard/business': typeof DashboardBusinessRoute
  '/dashboard/favorites': typeof DashboardFavoritesRoute
  '/dashboard/messages': typeof DashboardMessagesRoute
  '/dashboard/my-ads': typeof DashboardMyAdsRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/points': typeof DashboardPointsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/requests': typeof DashboardRequestsRoute
  '/dashboard/violations': typeof DashboardViolationsRoute
  '/invite/$token': typeof InviteTokenRoute
  '/stores/$slug': typeof StoresSlugRoute
  '/u/$username': typeof UUsernameRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/businesses/$id': typeof AdminBusinessesIdRoute
  '/admin/listings/$id': typeof AdminListingsIdRoute
  '/admin/reports/$id': typeof AdminReportsIdRoute
  '/admin/users/$id': typeof AdminUsersIdRoute
  '/admin/verifications/$id': typeof AdminVerificationsIdRoute
  '/dashboard/ads/new': typeof DashboardAdsNewRoute
  '/dashboard/reports/$id': typeof DashboardReportsIdRoute
  '/dashboard/store/catalog': typeof DashboardStoreCatalogRoute
  '/dashboard/store/new': typeof DashboardStoreNewRoute
  '/admin/reports/': typeof AdminReportsIndexRoute
  '/dashboard/reports/': typeof DashboardReportsIndexRoute
  '/dashboard/store/': typeof DashboardStoreIndexRoute
  '/dashboard/ads/$id/edit': typeof DashboardAdsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/audit': typeof AuditRoute
  '/auth': typeof AuthRoute
  '/choose-account': typeof ChooseAccountRoute
  '/contact': typeof ContactRoute
  '/help': typeof HelpRoute
  '/market-setup': typeof MarketSetupRoute
  '/me': typeof MeRoute
  '/more': typeof MoreRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/terms': typeof TermsRoute
  '/verify-invoice': typeof VerifyInvoiceRoute
  '/welcome': typeof WelcomeRoute
  '/admin/activities': typeof AdminActivitiesRoute
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/audit-log': typeof AdminAuditLogRoute
  '/admin/businesses': typeof AdminBusinessesRoute
  '/admin/content-rules': typeof AdminContentRulesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/geo': typeof AdminGeoRoute
  '/admin/listing-events': typeof AdminListingEventsRoute
  '/admin/listing-reports': typeof AdminListingReportsRoute
  '/admin/listings': typeof AdminListingsRoute
  '/admin/my-work': typeof AdminMyWorkRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/search': typeof AdminSearchRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/stores': typeof AdminStoresRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/verifications': typeof AdminVerificationsRoute
  '/admin/workforce': typeof AdminWorkforceRoute
  '/ads/$slug': typeof AdsSlugRoute
  '/business/new': typeof BusinessNewRoute
  '/businesses/$slug': typeof BusinessesSlugRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/dashboard/business': typeof DashboardBusinessRoute
  '/dashboard/favorites': typeof DashboardFavoritesRoute
  '/dashboard/messages': typeof DashboardMessagesRoute
  '/dashboard/my-ads': typeof DashboardMyAdsRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/points': typeof DashboardPointsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/requests': typeof DashboardRequestsRoute
  '/dashboard/violations': typeof DashboardViolationsRoute
  '/invite/$token': typeof InviteTokenRoute
  '/stores/$slug': typeof StoresSlugRoute
  '/u/$username': typeof UUsernameRoute
  '/admin': typeof AdminIndexRoute
  '/admin/businesses/$id': typeof AdminBusinessesIdRoute
  '/admin/listings/$id': typeof AdminListingsIdRoute
  '/admin/reports/$id': typeof AdminReportsIdRoute
  '/admin/users/$id': typeof AdminUsersIdRoute
  '/admin/verifications/$id': typeof AdminVerificationsIdRoute
  '/dashboard/ads/new': typeof DashboardAdsNewRoute
  '/dashboard/reports/$id': typeof DashboardReportsIdRoute
  '/dashboard/store/catalog': typeof DashboardStoreCatalogRoute
  '/dashboard/store/new': typeof DashboardStoreNewRoute
  '/admin/reports': typeof AdminReportsIndexRoute
  '/dashboard/reports': typeof DashboardReportsIndexRoute
  '/dashboard/store': typeof DashboardStoreIndexRoute
  '/dashboard/ads/$id/edit': typeof DashboardAdsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/audit': typeof AuditRoute
  '/auth': typeof AuthRoute
  '/choose-account': typeof ChooseAccountRoute
  '/contact': typeof ContactRoute
  '/help': typeof HelpRoute
  '/market-setup': typeof MarketSetupRoute
  '/me': typeof MeRoute
  '/more': typeof MoreRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/terms': typeof TermsRoute
  '/verify-invoice': typeof VerifyInvoiceRoute
  '/welcome': typeof WelcomeRoute
  '/admin/activities': typeof AdminActivitiesRoute
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/audit-log': typeof AdminAuditLogRoute
  '/admin/businesses': typeof AdminBusinessesRoute
  '/admin/content-rules': typeof AdminContentRulesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/geo': typeof AdminGeoRoute
  '/admin/listing-events': typeof AdminListingEventsRoute
  '/admin/listing-reports': typeof AdminListingReportsRoute
  '/admin/listings': typeof AdminListingsRoute
  '/admin/my-work': typeof AdminMyWorkRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/search': typeof AdminSearchRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/stores': typeof AdminStoresRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/verifications': typeof AdminVerificationsRoute
  '/admin/workforce': typeof AdminWorkforceRoute
  '/ads/$slug': typeof AdsSlugRoute
  '/business/new': typeof BusinessNewRoute
  '/businesses/$slug': typeof BusinessesSlugRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/dashboard/business': typeof DashboardBusinessRoute
  '/dashboard/favorites': typeof DashboardFavoritesRoute
  '/dashboard/messages': typeof DashboardMessagesRoute
  '/dashboard/my-ads': typeof DashboardMyAdsRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/points': typeof DashboardPointsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/requests': typeof DashboardRequestsRoute
  '/dashboard/violations': typeof DashboardViolationsRoute
  '/invite/$token': typeof InviteTokenRoute
  '/stores/$slug': typeof StoresSlugRoute
  '/u/$username': typeof UUsernameRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/businesses_/$id': typeof AdminBusinessesIdRoute
  '/admin/listings_/$id': typeof AdminListingsIdRoute
  '/admin/reports/$id': typeof AdminReportsIdRoute
  '/admin/users_/$id': typeof AdminUsersIdRoute
  '/admin/verifications_/$id': typeof AdminVerificationsIdRoute
  '/dashboard/ads/new': typeof DashboardAdsNewRoute
  '/dashboard/reports/$id': typeof DashboardReportsIdRoute
  '/dashboard/store/catalog': typeof DashboardStoreCatalogRoute
  '/dashboard/store/new': typeof DashboardStoreNewRoute
  '/admin/reports/': typeof AdminReportsIndexRoute
  '/dashboard/reports/': typeof DashboardReportsIndexRoute
  '/dashboard/store/': typeof DashboardStoreIndexRoute
  '/dashboard/ads/$id/edit': typeof DashboardAdsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/$'
    | '/about'
    | '/audit'
    | '/auth'
    | '/choose-account'
    | '/contact'
    | '/help'
    | '/market-setup'
    | '/me'
    | '/more'
    | '/privacy'
    | '/register'
    | '/search'
    | '/terms'
    | '/verify-invoice'
    | '/welcome'
    | '/admin/activities'
    | '/admin/attendance'
    | '/admin/audit-log'
    | '/admin/businesses'
    | '/admin/content-rules'
    | '/admin/dashboard'
    | '/admin/geo'
    | '/admin/listing-events'
    | '/admin/listing-reports'
    | '/admin/listings'
    | '/admin/my-work'
    | '/admin/roles'
    | '/admin/search'
    | '/admin/settings'
    | '/admin/stores'
    | '/admin/users'
    | '/admin/verifications'
    | '/admin/workforce'
    | '/ads/$slug'
    | '/business/new'
    | '/businesses/$slug'
    | '/categories/$slug'
    | '/dashboard/business'
    | '/dashboard/favorites'
    | '/dashboard/messages'
    | '/dashboard/my-ads'
    | '/dashboard/notifications'
    | '/dashboard/points'
    | '/dashboard/profile'
    | '/dashboard/requests'
    | '/dashboard/violations'
    | '/invite/$token'
    | '/stores/$slug'
    | '/u/$username'
    | '/admin/'
    | '/admin/businesses/$id'
    | '/admin/listings/$id'
    | '/admin/reports/$id'
    | '/admin/users/$id'
    | '/admin/verifications/$id'
    | '/dashboard/ads/new'
    | '/dashboard/reports/$id'
    | '/dashboard/store/catalog'
    | '/dashboard/store/new'
    | '/admin/reports/'
    | '/dashboard/reports/'
    | '/dashboard/store/'
    | '/dashboard/ads/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/about'
    | '/audit'
    | '/auth'
    | '/choose-account'
    | '/contact'
    | '/help'
    | '/market-setup'
    | '/me'
    | '/more'
    | '/privacy'
    | '/register'
    | '/search'
    | '/terms'
    | '/verify-invoice'
    | '/welcome'
    | '/admin/activities'
    | '/admin/attendance'
    | '/admin/audit-log'
    | '/admin/businesses'
    | '/admin/content-rules'
    | '/admin/dashboard'
    | '/admin/geo'
    | '/admin/listing-events'
    | '/admin/listing-reports'
    | '/admin/listings'
    | '/admin/my-work'
    | '/admin/roles'
    | '/admin/search'
    | '/admin/settings'
    | '/admin/stores'
    | '/admin/users'
    | '/admin/verifications'
    | '/admin/workforce'
    | '/ads/$slug'
    | '/business/new'
    | '/businesses/$slug'
    | '/categories/$slug'
    | '/dashboard/business'
    | '/dashboard/favorites'
    | '/dashboard/messages'
    | '/dashboard/my-ads'
    | '/dashboard/notifications'
    | '/dashboard/points'
    | '/dashboard/profile'
    | '/dashboard/requests'
    | '/dashboard/violations'
    | '/invite/$token'
    | '/stores/$slug'
    | '/u/$username'
    | '/admin'
    | '/admin/businesses/$id'
    | '/admin/listings/$id'
    | '/admin/reports/$id'
    | '/admin/users/$id'
    | '/admin/verifications/$id'
    | '/dashboard/ads/new'
    | '/dashboard/reports/$id'
    | '/dashboard/store/catalog'
    | '/dashboard/store/new'
    | '/admin/reports'
    | '/dashboard/reports'
    | '/dashboard/store'
    | '/dashboard/ads/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/$'
    | '/about'
    | '/audit'
    | '/auth'
    | '/choose-account'
    | '/contact'
    | '/help'
    | '/market-setup'
    | '/me'
    | '/more'
    | '/privacy'
    | '/register'
    | '/search'
    | '/terms'
    | '/verify-invoice'
    | '/welcome'
    | '/admin/activities'
    | '/admin/attendance'
    | '/admin/audit-log'
    | '/admin/businesses'
    | '/admin/content-rules'
    | '/admin/dashboard'
    | '/admin/geo'
    | '/admin/listing-events'
    | '/admin/listing-reports'
    | '/admin/listings'
    | '/admin/my-work'
    | '/admin/roles'
    | '/admin/search'
    | '/admin/settings'
    | '/admin/stores'
    | '/admin/users'
    | '/admin/verifications'
    | '/admin/workforce'
    | '/ads/$slug'
    | '/business/new'
    | '/businesses/$slug'
    | '/categories/$slug'
    | '/dashboard/business'
    | '/dashboard/favorites'
    | '/dashboard/messages'
    | '/dashboard/my-ads'
    | '/dashboard/notifications'
    | '/dashboard/points'
    | '/dashboard/profile'
    | '/dashboard/requests'
    | '/dashboard/violations'
    | '/invite/$token'
    | '/stores/$slug'
    | '/u/$username'
    | '/admin/'
    | '/admin/businesses_/$id'
    | '/admin/listings_/$id'
    | '/admin/reports/$id'
    | '/admin/users_/$id'
    | '/admin/verifications_/$id'
    | '/dashboard/ads/new'
    | '/dashboard/reports/$id'
    | '/dashboard/store/catalog'
    | '/dashboard/store/new'
    | '/admin/reports/'
    | '/dashboard/reports/'
    | '/dashboard/store/'
    | '/dashboard/ads/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  SplatRoute: typeof SplatRoute
  AboutRoute: typeof AboutRoute
  AuditRoute: typeof AuditRoute
  AuthRoute: typeof AuthRoute
  ChooseAccountRoute: typeof ChooseAccountRoute
  ContactRoute: typeof ContactRoute
  HelpRoute: typeof HelpRoute
  MarketSetupRoute: typeof MarketSetupRoute
  MeRoute: typeof MeRoute
  MoreRoute: typeof MoreRoute
  PrivacyRoute: typeof PrivacyRoute
  RegisterRoute: typeof RegisterRoute
  SearchRoute: typeof SearchRoute
  TermsRoute: typeof TermsRoute
  VerifyInvoiceRoute: typeof VerifyInvoiceRoute
  WelcomeRoute: typeof WelcomeRoute
  AdsSlugRoute: typeof AdsSlugRoute
  BusinessNewRoute: typeof BusinessNewRoute
  BusinessesSlugRoute: typeof BusinessesSlugRoute
  CategoriesSlugRoute: typeof CategoriesSlugRoute
  DashboardBusinessRoute: typeof DashboardBusinessRoute
  DashboardFavoritesRoute: typeof DashboardFavoritesRoute
  DashboardMessagesRoute: typeof DashboardMessagesRoute
  DashboardMyAdsRoute: typeof DashboardMyAdsRoute
  DashboardNotificationsRoute: typeof DashboardNotificationsRoute
  DashboardPointsRoute: typeof DashboardPointsRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardRequestsRoute: typeof DashboardRequestsRoute
  DashboardViolationsRoute: typeof DashboardViolationsRoute
  InviteTokenRoute: typeof InviteTokenRoute
  StoresSlugRoute: typeof StoresSlugRoute
  UUsernameRoute: typeof UUsernameRoute
  DashboardAdsNewRoute: typeof DashboardAdsNewRoute
  DashboardReportsIdRoute: typeof DashboardReportsIdRoute
  DashboardStoreCatalogRoute: typeof DashboardStoreCatalogRoute
  DashboardStoreNewRoute: typeof DashboardStoreNewRoute
  DashboardReportsIndexRoute: typeof DashboardReportsIndexRoute
  DashboardStoreIndexRoute: typeof DashboardStoreIndexRoute
  DashboardAdsIdEditRoute: typeof DashboardAdsIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/choose-account': {
      id: '/choose-account'
      path: '/choose-account'
      fullPath: '/choose-account'
      preLoaderRoute: typeof ChooseAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market-setup': {
      id: '/market-setup'
      path: '/market-setup'
      fullPath: '/market-setup'
      preLoaderRoute: typeof MarketSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/more': {
      id: '/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof MoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-invoice': {
      id: '/verify-invoice'
      path: '/verify-invoice'
      fullPath: '/verify-invoice'
      preLoaderRoute: typeof VerifyInvoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/activities': {
      id: '/admin/activities'
      path: '/activities'
      fullPath: '/admin/activities'
      preLoaderRoute: typeof AdminActivitiesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/attendance': {
      id: '/admin/attendance'
      path: '/attendance'
      fullPath: '/admin/attendance'
      preLoaderRoute: typeof AdminAttendanceRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/audit-log': {
      id: '/admin/audit-log'
      path: '/audit-log'
      fullPath: '/admin/audit-log'
      preLoaderRoute: typeof AdminAuditLogRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/businesses': {
      id: '/admin/businesses'
      path: '/businesses'
      fullPath: '/admin/businesses'
      preLoaderRoute: typeof AdminBusinessesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/content-rules': {
      id: '/admin/content-rules'
      path: '/content-rules'
      fullPath: '/admin/content-rules'
      preLoaderRoute: typeof AdminContentRulesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/geo': {
      id: '/admin/geo'
      path: '/geo'
      fullPath: '/admin/geo'
      preLoaderRoute: typeof AdminGeoRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/listing-events': {
      id: '/admin/listing-events'
      path: '/listing-events'
      fullPath: '/admin/listing-events'
      preLoaderRoute: typeof AdminListingEventsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/listing-reports': {
      id: '/admin/listing-reports'
      path: '/listing-reports'
      fullPath: '/admin/listing-reports'
      preLoaderRoute: typeof AdminListingReportsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/listings': {
      id: '/admin/listings'
      path: '/listings'
      fullPath: '/admin/listings'
      preLoaderRoute: typeof AdminListingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/my-work': {
      id: '/admin/my-work'
      path: '/my-work'
      fullPath: '/admin/my-work'
      preLoaderRoute: typeof AdminMyWorkRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/roles': {
      id: '/admin/roles'
      path: '/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminRolesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/search': {
      id: '/admin/search'
      path: '/search'
      fullPath: '/admin/search'
      preLoaderRoute: typeof AdminSearchRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/stores': {
      id: '/admin/stores'
      path: '/stores'
      fullPath: '/admin/stores'
      preLoaderRoute: typeof AdminStoresRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/verifications': {
      id: '/admin/verifications'
      path: '/verifications'
      fullPath: '/admin/verifications'
      preLoaderRoute: typeof AdminVerificationsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/workforce': {
      id: '/admin/workforce'
      path: '/workforce'
      fullPath: '/admin/workforce'
      preLoaderRoute: typeof AdminWorkforceRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/ads/$slug': {
      id: '/ads/$slug'
      path: '/ads/$slug'
      fullPath: '/ads/$slug'
      preLoaderRoute: typeof AdsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/new': {
      id: '/business/new'
      path: '/business/new'
      fullPath: '/business/new'
      preLoaderRoute: typeof BusinessNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/businesses/$slug': {
      id: '/businesses/$slug'
      path: '/businesses/$slug'
      fullPath: '/businesses/$slug'
      preLoaderRoute: typeof BusinessesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/$slug': {
      id: '/categories/$slug'
      path: '/categories/$slug'
      fullPath: '/categories/$slug'
      preLoaderRoute: typeof CategoriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/business': {
      id: '/dashboard/business'
      path: '/dashboard/business'
      fullPath: '/dashboard/business'
      preLoaderRoute: typeof DashboardBusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/favorites': {
      id: '/dashboard/favorites'
      path: '/dashboard/favorites'
      fullPath: '/dashboard/favorites'
      preLoaderRoute: typeof DashboardFavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/messages': {
      id: '/dashboard/messages'
      path: '/dashboard/messages'
      fullPath: '/dashboard/messages'
      preLoaderRoute: typeof DashboardMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/my-ads': {
      id: '/dashboard/my-ads'
      path: '/dashboard/my-ads'
      fullPath: '/dashboard/my-ads'
      preLoaderRoute: typeof DashboardMyAdsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/notifications': {
      id: '/dashboard/notifications'
      path: '/dashboard/notifications'
      fullPath: '/dashboard/notifications'
      preLoaderRoute: typeof DashboardNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/points': {
      id: '/dashboard/points'
      path: '/dashboard/points'
      fullPath: '/dashboard/points'
      preLoaderRoute: typeof DashboardPointsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/dashboard/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/requests': {
      id: '/dashboard/requests'
      path: '/dashboard/requests'
      fullPath: '/dashboard/requests'
      preLoaderRoute: typeof DashboardRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/violations': {
      id: '/dashboard/violations'
      path: '/dashboard/violations'
      fullPath: '/dashboard/violations'
      preLoaderRoute: typeof DashboardViolationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stores/$slug': {
      id: '/stores/$slug'
      path: '/stores/$slug'
      fullPath: '/stores/$slug'
      preLoaderRoute: typeof StoresSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$username': {
      id: '/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof UUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/businesses_/$id': {
      id: '/admin/businesses_/$id'
      path: '/businesses/$id'
      fullPath: '/admin/businesses/$id'
      preLoaderRoute: typeof AdminBusinessesIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/listings_/$id': {
      id: '/admin/listings_/$id'
      path: '/listings/$id'
      fullPath: '/admin/listings/$id'
      preLoaderRoute: typeof AdminListingsIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/reports/': {
      id: '/admin/reports/'
      path: '/reports'
      fullPath: '/admin/reports/'
      preLoaderRoute: typeof AdminReportsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/reports/$id': {
      id: '/admin/reports/$id'
      path: '/reports/$id'
      fullPath: '/admin/reports/$id'
      preLoaderRoute: typeof AdminReportsIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/users_/$id': {
      id: '/admin/users_/$id'
      path: '/users/$id'
      fullPath: '/admin/users/$id'
      preLoaderRoute: typeof AdminUsersIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/verifications_/$id': {
      id: '/admin/verifications_/$id'
      path: '/verifications/$id'
      fullPath: '/admin/verifications/$id'
      preLoaderRoute: typeof AdminVerificationsIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/dashboard/ads/new': {
      id: '/dashboard/ads/new'
      path: '/dashboard/ads/new'
      fullPath: '/dashboard/ads/new'
      preLoaderRoute: typeof DashboardAdsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/reports/': {
      id: '/dashboard/reports/'
      path: '/dashboard/reports'
      fullPath: '/dashboard/reports/'
      preLoaderRoute: typeof DashboardReportsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/reports/$id': {
      id: '/dashboard/reports/$id'
      path: '/dashboard/reports/$id'
      fullPath: '/dashboard/reports/$id'
      preLoaderRoute: typeof DashboardReportsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/store/': {
      id: '/dashboard/store/'
      path: '/dashboard/store'
      fullPath: '/dashboard/store/'
      preLoaderRoute: typeof DashboardStoreIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/store/catalog': {
      id: '/dashboard/store/catalog'
      path: '/dashboard/store/catalog'
      fullPath: '/dashboard/store/catalog'
      preLoaderRoute: typeof DashboardStoreCatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/store/new': {
      id: '/dashboard/store/new'
      path: '/dashboard/store/new'
      fullPath: '/dashboard/store/new'
      preLoaderRoute: typeof DashboardStoreNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/ads/$id/edit': {
      id: '/dashboard/ads/$id/edit'
      path: '/dashboard/ads/$id/edit'
      fullPath: '/dashboard/ads/$id/edit'
      preLoaderRoute: typeof DashboardAdsIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteRouteChildren {
  AdminActivitiesRoute: typeof AdminActivitiesRoute
  AdminAttendanceRoute: typeof AdminAttendanceRoute
  AdminAuditLogRoute: typeof AdminAuditLogRoute
  AdminBusinessesRoute: typeof AdminBusinessesRoute
  AdminContentRulesRoute: typeof AdminContentRulesRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminGeoRoute: typeof AdminGeoRoute
  AdminListingEventsRoute: typeof AdminListingEventsRoute
  AdminListingReportsRoute: typeof AdminListingReportsRoute
  AdminListingsRoute: typeof AdminListingsRoute
  AdminMyWorkRoute: typeof AdminMyWorkRoute
  AdminRolesRoute: typeof AdminRolesRoute
  AdminSearchRoute: typeof AdminSearchRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminStoresRoute: typeof AdminStoresRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminVerificationsRoute: typeof AdminVerificationsRoute
  AdminWorkforceRoute: typeof AdminWorkforceRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminBusinessesIdRoute: typeof AdminBusinessesIdRoute
  AdminListingsIdRoute: typeof AdminListingsIdRoute
  AdminReportsIdRoute: typeof AdminReportsIdRoute
  AdminUsersIdRoute: typeof AdminUsersIdRoute
  AdminVerificationsIdRoute: typeof AdminVerificationsIdRoute
  AdminReportsIndexRoute: typeof AdminReportsIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminActivitiesRoute: AdminActivitiesRoute,
  AdminAttendanceRoute: AdminAttendanceRoute,
  AdminAuditLogRoute: AdminAuditLogRoute,
  AdminBusinessesRoute: AdminBusinessesRoute,
  AdminContentRulesRoute: AdminContentRulesRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminGeoRoute: AdminGeoRoute,
  AdminListingEventsRoute: AdminListingEventsRoute,
  AdminListingReportsRoute: AdminListingReportsRoute,
  AdminListingsRoute: AdminListingsRoute,
  AdminMyWorkRoute: AdminMyWorkRoute,
  AdminRolesRoute: AdminRolesRoute,
  AdminSearchRoute: AdminSearchRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminStoresRoute: AdminStoresRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminVerificationsRoute: AdminVerificationsRoute,
  AdminWorkforceRoute: AdminWorkforceRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminBusinessesIdRoute: AdminBusinessesIdRoute,
  AdminListingsIdRoute: AdminListingsIdRoute,
  AdminReportsIdRoute: AdminReportsIdRoute,
  AdminUsersIdRoute: AdminUsersIdRoute,
  AdminVerificationsIdRoute: AdminVerificationsIdRoute,
  AdminReportsIndexRoute: AdminReportsIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  SplatRoute: SplatRoute,
  AboutRoute: AboutRoute,
  AuditRoute: AuditRoute,
  AuthRoute: AuthRoute,
  ChooseAccountRoute: ChooseAccountRoute,
  ContactRoute: ContactRoute,
  HelpRoute: HelpRoute,
  MarketSetupRoute: MarketSetupRoute,
  MeRoute: MeRoute,
  MoreRoute: MoreRoute,
  PrivacyRoute: PrivacyRoute,
  RegisterRoute: RegisterRoute,
  SearchRoute: SearchRoute,
  TermsRoute: TermsRoute,
  VerifyInvoiceRoute: VerifyInvoiceRoute,
  WelcomeRoute: WelcomeRoute,
  AdsSlugRoute: AdsSlugRoute,
  BusinessNewRoute: BusinessNewRoute,
  BusinessesSlugRoute: BusinessesSlugRoute,
  CategoriesSlugRoute: CategoriesSlugRoute,
  DashboardBusinessRoute: DashboardBusinessRoute,
  DashboardFavoritesRoute: DashboardFavoritesRoute,
  DashboardMessagesRoute: DashboardMessagesRoute,
  DashboardMyAdsRoute: DashboardMyAdsRoute,
  DashboardNotificationsRoute: DashboardNotificationsRoute,
  DashboardPointsRoute: DashboardPointsRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardRequestsRoute: DashboardRequestsRoute,
  DashboardViolationsRoute: DashboardViolationsRoute,
  InviteTokenRoute: InviteTokenRoute,
  StoresSlugRoute: StoresSlugRoute,
  UUsernameRoute: UUsernameRoute,
  DashboardAdsNewRoute: DashboardAdsNewRoute,
  DashboardReportsIdRoute: DashboardReportsIdRoute,
  DashboardStoreCatalogRoute: DashboardStoreCatalogRoute,
  DashboardStoreNewRoute: DashboardStoreNewRoute,
  DashboardReportsIndexRoute: DashboardReportsIndexRoute,
  DashboardStoreIndexRoute: DashboardStoreIndexRoute,
  DashboardAdsIdEditRoute: DashboardAdsIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
