-- =========================================================
-- 1) SUPPLIERS
-- =========================================================
CREATE TABLE public.suppliers (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name_ar text NOT NULL,
  name_en text,
  tax_number text,
  commercial_reg text,
  unified_number text,
  phone text,
  email text,
  city text,
  address text,
  notes text,
  is_active boolean NOT NULL DEFAULT true,
  created_by uuid,
  deleted_at timestamptz,
  delete_reason text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

GRANT SELECT, INSERT, UPDATE ON public.suppliers TO authenticated;
GRANT ALL ON public.suppliers TO service_role;
ALTER TABLE public.suppliers ENABLE ROW LEVEL SECURITY;

CREATE UNIQUE INDEX suppliers_tax_number_unique
  ON public.suppliers (tax_number)
  WHERE tax_number IS NOT NULL AND btrim(tax_number) <> '' AND deleted_at IS NULL;

CREATE POLICY "suppliers_select_staff" ON public.suppliers
  FOR SELECT TO authenticated
  USING (public.is_accountant() OR public.has_role(auth.uid(), 'employee'));

CREATE POLICY "suppliers_insert_staff" ON public.suppliers
  FOR INSERT TO authenticated
  WITH CHECK (public.is_accountant() OR public.has_role(auth.uid(), 'employee'));

CREATE POLICY "suppliers_update_staff" ON public.suppliers
  FOR UPDATE TO authenticated
  USING (public.is_accountant() OR public.has_role(auth.uid(), 'employee'))
  WITH CHECK (public.is_accountant() OR public.has_role(auth.uid(), 'employee'));

CREATE TRIGGER suppliers_set_updated_at
  BEFORE UPDATE ON public.suppliers
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

-- =========================================================
-- 2) INVOICE NUMBER NORMALIZATION
-- =========================================================
CREATE OR REPLACE FUNCTION public.normalize_doc_no(p_value text)
RETURNS text
LANGUAGE sql
IMMUTABLE
SECURITY INVOKER
SET search_path = public
AS $$
  SELECT nullif(
    upper(
      regexp_replace(
        translate(
          coalesce(p_value, ''),
          '٠١٢٣٤٥٦٧٨٩۰۱۲۳۴۵۶۷۸۹',
          '01234567890123456789'
        ),
        '[^0-9A-Za-z\u0621-\u064A]', '', 'g'
      )
    ),
    ''
  )
$$;
GRANT EXECUTE ON FUNCTION public.normalize_doc_no(text) TO PUBLIC;

-- =========================================================
-- 3) INVOICES
-- =========================================================
CREATE TABLE public.invoices (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  internal_no bigint GENERATED BY DEFAULT AS IDENTITY,
  supplier_id uuid NOT NULL REFERENCES public.suppliers(id),
  invoice_no text NOT NULL,
  invoice_no_norm text GENERATED ALWAYS AS (public.normalize_doc_no(invoice_no)) STORED,
  invoice_date date NOT NULL,
  project_id uuid NOT NULL REFERENCES public.projects(id),
  supervisor_id uuid REFERENCES public.supervisors(id),
  amount_before_tax numeric(14,2) NOT NULL DEFAULT 0,
  tax_amount numeric(14,2) NOT NULL DEFAULT 0,
  total_amount numeric(14,2) NOT NULL DEFAULT 0,
  description text,
  status public.record_status NOT NULL DEFAULT 'draft',
  duplicate_reason text,
  client_token text,
  created_by uuid,
  updated_by uuid,
  deleted_at timestamptz,
  delete_reason text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

GRANT SELECT, INSERT, UPDATE ON public.invoices TO authenticated;
GRANT ALL ON public.invoices TO service_role;
ALTER TABLE public.invoices ENABLE ROW LEVEL SECURITY;

CREATE UNIQUE INDEX invoices_internal_no_unique ON public.invoices (internal_no);
CREATE UNIQUE INDEX invoices_client_token_unique ON public.invoices (client_token) WHERE client_token IS NOT NULL;

-- duplicate guard: same supplier + date + normalized number, unless the accountant
-- explicitly confirmed the duplicate with a reason
CREATE UNIQUE INDEX invoices_duplicate_guard
  ON public.invoices (supplier_id, invoice_date, invoice_no_norm)
  WHERE deleted_at IS NULL AND duplicate_reason IS NULL;

CREATE INDEX invoices_project_idx ON public.invoices (project_id);
CREATE INDEX invoices_supervisor_idx ON public.invoices (supervisor_id);
CREATE INDEX invoices_supplier_idx ON public.invoices (supplier_id);

CREATE POLICY "invoices_select_scoped" ON public.invoices
  FOR SELECT TO authenticated
  USING (public.is_accountant() OR public.can_access_project(project_id));

CREATE POLICY "invoices_insert_scoped" ON public.invoices
  FOR INSERT TO authenticated
  WITH CHECK (public.is_accountant() OR public.can_access_project(project_id));

CREATE POLICY "invoices_update_scoped" ON public.invoices
  FOR UPDATE TO authenticated
  USING (public.is_accountant() OR public.can_access_project(project_id))
  WITH CHECK (public.is_accountant() OR public.can_access_project(project_id));

CREATE TRIGGER invoices_set_updated_at
  BEFORE UPDATE ON public.invoices
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

-- totals + workflow guard
CREATE OR REPLACE FUNCTION public.invoices_guard()
RETURNS trigger
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = public
AS $$
DECLARE
  v_is_acc boolean := public.is_accountant();
BEGIN
  NEW.total_amount := round(coalesce(NEW.amount_before_tax, 0) + coalesce(NEW.tax_amount, 0), 2);

  IF TG_OP = 'INSERT' THEN
    IF NOT v_is_acc AND NEW.status NOT IN ('draft', 'under_review') THEN
      RAISE EXCEPTION 'employee_cannot_set_status';
    END IF;
    IF NEW.duplicate_reason IS NOT NULL AND NOT v_is_acc THEN
      RAISE EXCEPTION 'duplicate_override_requires_accountant';
    END IF;
    RETURN NEW;
  END IF;

  -- UPDATE
  IF NOT v_is_acc THEN
    IF OLD.status NOT IN ('draft', 'returned') THEN
      RAISE EXCEPTION 'employee_cannot_edit_locked_invoice';
    END IF;
    IF NEW.status NOT IN ('draft', 'under_review') THEN
      RAISE EXCEPTION 'employee_cannot_set_status';
    END IF;
    IF NEW.duplicate_reason IS DISTINCT FROM OLD.duplicate_reason THEN
      RAISE EXCEPTION 'duplicate_override_requires_accountant';
    END IF;
  END IF;

  -- an approved invoice's core fields can never change silently
  IF OLD.status = 'approved' AND NEW.status = 'approved' THEN
    IF NEW.supplier_id IS DISTINCT FROM OLD.supplier_id
       OR NEW.invoice_no IS DISTINCT FROM OLD.invoice_no
       OR NEW.invoice_date IS DISTINCT FROM OLD.invoice_date
       OR NEW.amount_before_tax IS DISTINCT FROM OLD.amount_before_tax
       OR NEW.tax_amount IS DISTINCT FROM OLD.tax_amount THEN
      RAISE EXCEPTION 'approved_invoice_is_locked';
    END IF;
  END IF;

  -- status change reasons
  IF NEW.status IS DISTINCT FROM OLD.status THEN
    IF NEW.status IN ('returned', 'cancelled') AND coalesce(btrim(NEW.description), '') = '' AND TRUE THEN
      NULL; -- note is stored in invoice_status_history, validated there
    END IF;
    NEW.updated_by := auth.uid();
  END IF;

  RETURN NEW;
END;
$$;

CREATE TRIGGER invoices_guard_trg
  BEFORE INSERT OR UPDATE ON public.invoices
  FOR EACH ROW EXECUTE FUNCTION public.invoices_guard();

-- =========================================================
-- 4) INVOICE STATUS HISTORY
-- =========================================================
CREATE TABLE public.invoice_status_history (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  invoice_id uuid NOT NULL REFERENCES public.invoices(id) ON DELETE CASCADE,
  from_status public.record_status,
  to_status public.record_status NOT NULL,
  note text,
  actor_id uuid,
  created_at timestamptz NOT NULL DEFAULT now()
);

GRANT SELECT, INSERT ON public.invoice_status_history TO authenticated;
GRANT ALL ON public.invoice_status_history TO service_role;
ALTER TABLE public.invoice_status_history ENABLE ROW LEVEL SECURITY;

CREATE INDEX invoice_status_history_invoice_idx ON public.invoice_status_history (invoice_id);

CREATE POLICY "invoice_history_select_scoped" ON public.invoice_status_history
  FOR SELECT TO authenticated
  USING (EXISTS (
    SELECT 1 FROM public.invoices i
    WHERE i.id = invoice_status_history.invoice_id
      AND (public.is_accountant() OR public.can_access_project(i.project_id))
  ));

CREATE POLICY "invoice_history_insert_scoped" ON public.invoice_status_history
  FOR INSERT TO authenticated
  WITH CHECK (
    actor_id = auth.uid()
    AND EXISTS (
      SELECT 1 FROM public.invoices i
      WHERE i.id = invoice_status_history.invoice_id
        AND (public.is_accountant() OR public.can_access_project(i.project_id))
    )
    AND (public.is_accountant() OR to_status IN ('draft', 'under_review'))
  );

-- =========================================================
-- 5) CUSTODY <-> INVOICE SETTLEMENT
-- =========================================================
ALTER TABLE public.custody_transactions
  ADD COLUMN invoice_id uuid REFERENCES public.invoices(id);

CREATE INDEX custody_transactions_invoice_idx ON public.custody_transactions (invoice_id);

-- expose invoice_id through the custody effects view
CREATE OR REPLACE VIEW public.custody_txn_effects
WITH (security_invoker = true) AS
SELECT t.id,
    t.serial_no,
    t.supervisor_id,
    t.project_id,
    t.txn_type,
    t.amount,
    t.txn_date,
    t.status,
    t.reason,
    t.notes_ar,
    t.deleted_at,
    t.reversal_of_id,
    o.serial_no AS reversal_of_serial,
    o.txn_type AS reversal_of_type,
    r.id AS reversed_by_id,
    r.serial_no AS reversed_by_serial,
    (CASE
        WHEN t.txn_type = 'reversal'::custody_txn_type THEN - public.custody_base_effect(o.txn_type, t.amount)
        ELSE public.custody_base_effect(t.txn_type, t.amount)
     END)::numeric(14,2) AS signed_amount,
    t.invoice_id,
    o.invoice_id AS reversal_of_invoice_id
   FROM public.custody_transactions t
     LEFT JOIN public.custody_transactions o ON o.id = t.reversal_of_id
     LEFT JOIN public.custody_transactions r ON r.reversal_of_id = t.id AND r.deleted_at IS NULL;

-- settled amount = approved settlement effects tied to the invoice (reversals flip sign)
CREATE OR REPLACE FUNCTION public.invoice_settled_amount(p_invoice_id uuid)
RETURNS numeric
LANGUAGE sql
STABLE
SECURITY INVOKER
SET search_path = public
AS $$
  SELECT coalesce(sum(-e.signed_amount), 0)
  FROM public.custody_txn_effects e
  WHERE coalesce(e.invoice_id, e.reversal_of_invoice_id) = p_invoice_id
    AND e.status = 'approved'
    AND e.deleted_at IS NULL
$$;
GRANT EXECUTE ON FUNCTION public.invoice_settled_amount(uuid) TO PUBLIC;

CREATE OR REPLACE FUNCTION public.custody_settlement_guard()
RETURNS trigger
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = public
AS $$
DECLARE
  v_total numeric;
  v_settled numeric;
  v_status public.record_status;
BEGIN
  IF NEW.invoice_id IS NULL THEN
    RETURN NEW;
  END IF;

  IF NOT public.is_accountant() THEN
    RAISE EXCEPTION 'settlement_requires_accountant';
  END IF;

  SELECT total_amount, status INTO v_total, v_status
  FROM public.invoices WHERE id = NEW.invoice_id;

  IF v_status IS DISTINCT FROM 'approved' THEN
    RAISE EXCEPTION 'settlement_requires_approved_invoice';
  END IF;

  IF NEW.txn_type = 'settlement' THEN
    SELECT public.invoice_settled_amount(NEW.invoice_id) INTO v_settled;
    IF v_settled + coalesce(NEW.amount, 0) > v_total + 0.005 THEN
      RAISE EXCEPTION 'settlement_exceeds_invoice_total';
    END IF;
  END IF;

  RETURN NEW;
END;
$$;

CREATE TRIGGER custody_settlement_guard_trg
  BEFORE INSERT ON public.custody_transactions
  FOR EACH ROW EXECUTE FUNCTION public.custody_settlement_guard();

-- expose invoice link + settlement summary
CREATE OR REPLACE VIEW public.invoice_settlements
WITH (security_invoker = true) AS
SELECT
  i.id AS invoice_id,
  i.total_amount,
  public.invoice_settled_amount(i.id) AS settled_amount,
  round(i.total_amount - public.invoice_settled_amount(i.id), 2) AS remaining_amount
FROM public.invoices i
WHERE i.deleted_at IS NULL;

GRANT SELECT ON public.invoice_settlements TO authenticated;
GRANT SELECT ON public.invoice_settlements TO service_role;