REVOKE EXECUTE ON FUNCTION public.mkt_user_can(uuid, text) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.mkt_workforce_manage() FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.mkt_staff_on_leave(uuid) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.mkt_workforce_open_count(uuid) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.mkt_workforce_pick_assignee(text) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.mkt_workforce_enqueue(text, uuid, text, timestamptz) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.mkt_workforce_set_progress(text, uuid, text) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.mkt_workforce_set_priority(text, uuid, text, text) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.mkt_workforce_distribute(text, integer) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.mkt_workforce_set_staff(uuid, text, integer, boolean, text, text, text) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.mkt_workforce_add_leave(uuid, text, date, date, text, uuid) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.mkt_workforce_cancel_leave(uuid, text) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.mkt_workforce_staff() FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.mkt_workforce_queue(text, text, integer) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.mkt_workforce_overview() FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.mkt_staff_leave_validate() FROM PUBLIC, anon;