// This file is automatically generated. Keep client-side credentials publishable only.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";
import { createSupabaseAuthStorage } from "@/lib/native-auth-storage";
import { validatedSupabaseUrl } from "@/lib/supabase-url-policy";

function decodeJwtPayload(value: string): Record<string, unknown> | null {
  const payload = value.split(".")[1];
  if (!payload) return null;

  try {
    const normalized = payload.replace(/-/g, "+").replace(/_/g, "/");
    const padded = normalized.padEnd(Math.ceil(normalized.length / 4) * 4, "=");
    const json =
      typeof atob === "function"
        ? atob(padded)
        : Buffer.from(padded, "base64").toString("utf8");
    return JSON.parse(json) as Record<string, unknown>;
  } catch {
    return null;
  }
}

function isOpaquePublishableKey(value: string): boolean {
  return value.startsWith("sb_publishable_");
}

function assertPublishableClientKey(value: string): void {
  if (value.startsWith("sb_secret_")) {
    throw new Error("A Supabase secret key must never be bundled into the client application.");
  }

  if (isOpaquePublishableKey(value)) return;

  const payload = decodeJwtPayload(value);
  if (payload?.role === "anon") return;

  throw new Error("The client application requires a Supabase publishable or legacy anon key.");
}

function createSupabaseFetch(supabaseKey: string, supabaseOrigin: string): typeof fetch {
  return async (input, init) => {
    const requestUrl =
      typeof Request !== "undefined" && input instanceof Request
        ? input.url
        : input instanceof URL
          ? input.href
          : String(input);
    const target = new URL(requestUrl, supabaseOrigin);

    if (target.origin !== supabaseOrigin) {
      throw new Error("Blocked a Supabase request to an unapproved origin.");
    }

    const headers = new Headers(
      typeof Request !== "undefined" && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((headerValue, key) => headers.set(key, headerValue));
    }

    // Opaque publishable keys are API keys and must not be sent as bearer tokens.
    if (
      isOpaquePublishableKey(supabaseKey) &&
      headers.get("Authorization") === `Bearer ${supabaseKey}`
    ) {
      headers.delete("Authorization");
    }

    headers.set("apikey", supabaseKey);

    return fetch(input, {
      ...init,
      headers,
      credentials: "omit",
      redirect: "error",
      referrerPolicy: "no-referrer",
    });
  };
}

function createSupabaseClient() {
  const serverEnv = typeof process !== "undefined" ? process.env : undefined;
  const rawUrl = import.meta.env["VITE_SUPABASE_URL"] || serverEnv?.["SUPABASE_URL"];
  const publishableKey =
    import.meta.env["VITE_SUPABASE_PUBLISHABLE_KEY"] ||
    serverEnv?.["SUPABASE_PUBLISHABLE_KEY"];
  const expectedProjectRef =
    import.meta.env["VITE_SUPABASE_PROJECT_ID"] || serverEnv?.["SUPABASE_PROJECT_ID"];

  if (!rawUrl || !publishableKey) {
    const missing = [
      ...(!rawUrl ? ["SUPABASE_URL"] : []),
      ...(!publishableKey ? ["SUPABASE_PUBLISHABLE_KEY"] : []),
    ];
    throw new Error(`Missing Supabase environment variable(s): ${missing.join(", ")}.`);
  }

  assertPublishableClientKey(publishableKey);
  const supabaseOrigin = validatedSupabaseUrl(rawUrl, expectedProjectRef, import.meta.env.DEV);

  return createClient<Database>(supabaseOrigin, publishableKey, {
    global: {
      fetch: createSupabaseFetch(publishableKey, supabaseOrigin),
    },
    auth: {
      storage: createSupabaseAuthStorage(),
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
